### ISSUE TITLE
FTS won't start due to non-existing folder in config.

### ISSUE THREAD

**Issue by fieldmapper** [FreeTAKTeam/FreeTakServer#100]
https://github.com/FreeTAKTeam/FreeTakServer/blob/pypi/FreeTAKServer/controllers/configuration/MainConfig.py

Line 19:

From:    ` DBFilePath = str(r'/home/root/FTSDataBase.db')`
To:     `DBFilePath = str(r'/root/FTSDataBase.db')`

Since docs suggest doing `sudo` anyway.

**Comment by naman108** [comment]
this has been implemented
