### ISSUE TITLE
Client 'Error connecting to <server friendly name> (connection to host timed out)'

### ISSUE THREAD

**Issue by hamiltra** [FreeTAKTeam/FreeTakServer#104]
I'm hosting and evaluating FreeTAK Server and clients for emergency preparedness use. As such, I will have a mix of WinTak and ATAK clients connecting to the server. FTS Server and Android clients appear to live happily together but once I add WinTak there appears to be a data corruption causing a disconnection issue that starts. Here is the testing that I have performed.

Day 1:
- Scraped FTS server from RPi4B and started afresh. (Removed entire FreeTAKServer, logs and database)
- Setup configuration to use Python 3.7 and set database location
- Setup Android clients 1 and 3 to connect to server
- Tested each for basic functionality while continuously connected to the server. Verified chat communications.
- No XMPP, No VOIP, No email configured on clients

Allowed server to run overnight

Day 2:
 - Verified server is running and connected with Android Client 1
 - Started WinTak on Windows connected to same server
 - After 10 minutes or so all clients start receiving errors and disconnect/reconnect continuously at a periodic interval

What I found prior to this is that DataPackages were causing issues (or so I thought). For this testing scenario above, no DataPackages were uploaded but instead is a connectivity and light use case test.

Please advise if you require logs (debug or otherwise) or need a retest.

========================================================
Hardware and Software Configuration:
FTS:
 RPi 4B, 
 Raspbian Buster, 
 latest packages, 
 Python 3.7,
 FreeTAK Server-1.3 RC 6

Client 1:
 Motorola Moto z4 (Android)
 ATAK 4.2.0.4 from Play Store
 No XMPP, Email or VoIP configured

Client 2:
 Win10 Laptop,
 WinTak 4.0.1.231
 Unloaded TakChat

Client 3:
 Asus ZenFolio Z8 (Android)
ATAK XXXX from Playstore

Server connection across clients:
 DNS address on atak.local (yes it resolves)
 TCP connection
 Port 8087 (same as server configuration)
 No creds
 No SSL

**Comment by naman108** [comment]
yes if you could send post warning logs that would be very help full.

**Comment by hamiltra** [comment]
FTS_warning.log.1 shows an error @ 05:11AM then abuptly stops which is when the disconnections begin:

ERROR : 2020-12-23 04:01:43,626 : Orchestrator.py:159 : there has been an error in a clients connectionerror in the creation of client information
ERROR : 2020-12-23 04:01:43,629 : Orchestrator.py:469 : exception in receive connection data processing within main run function error in connection data processing data is -1
ERROR : 2020-12-23 04:02:23,931 : Orchestrator.py:159 : there has been an error in a clients connectionerror in the creation of client information
ERROR : 2020-12-23 04:02:23,934 : Orchestrator.py:469 : exception in receive connection data processing within main run function error in connection data processing data is -1
ERROR : 2020-12-23 04:03:04,261 : Orchestrator.py:159 : there has been an error in a clients connectionerror in the creation of client information
ERROR : 2020-12-23 04:03:04,264 : Orchestrator.py:469 : exception in receive connection data processing within main run function error in connection data processing data is -1
ERROR : 2020-12-23 04:03:44,602 : Orchestrator.py:159 : there has been an error in a clients connectionerror in the creation of client information
ERROR : 2020-12-23 04:03:44,605 : Orchestrator.py:469 : exception in receive connection data processing within main run function error in connection data processing data is -1
ERROR : 2020-12-23 05:11:44,862 : Orchestrator.py:305 : there has been an error in the reception of data in the monitoring of pipes B'int' object has no attribute 'type'
ERROR : 2020-12-23 05:11:44,867 : Orchestrator.py:469 : exception in receive connection data processing within main run function error in connection data processing data is -1

**Comment by naman108** [comment]
could you post the other warning logs aswell.

**Comment by brothercorvo** [comment]
deactivate the TAKchat in wintak and you should be fine

**Comment by hamiltra** [comment]
TakChat is deactivated as described above.

**Comment by hamiltra** [comment]
From FTS_debug.log ==> 
INFO : 2020-12-23 04:03:44,595 : Orchestrator.py:134 : client has connected
ERROR : 2020-12-23 04:03:44,602 : Orchestrator.py:159 : there has been an error in a clients connectionerror in the creation of client information
ERROR : 2020-12-23 04:03:44,605 : Orchestrator.py:469 : exception in receive connection data processing within main run function error in connection data processing data is -1
ERROR : 2020-12-23 05:11:44,862 : Orchestrator.py:305 : there has been an error in the reception of data in the monitoring of pipes B'int' object has no attribute 'type'
ERROR : 2020-12-23 05:11:44,867 : Orchestrator.py:469 : exception in receive connection data processing within main run function error in connection data processing data is -1
INFO : 2020-12-23 05:12:00,253 : Orchestrator.py:134 : client has connected
INFO : 2020-12-23 05:12:00,274 : Orchestrator.py:151 : finished establishing connectionWE6ACS
DEBUG : 2020-12-23 05:12:00,292 : Orchestrator.py:462 : connection data from client WE6ACS successfully processed
INFO : 2020-12-23 05:13:59,035 : Orchestrator.py:134 : client has connected
INFO : 2020-12-23 05:13:59,046 : Orchestrator.py:151 : finished establishing connectionNEVIN
DEBUG : 2020-12-23 05:13:59,056 : Orchestrator.py:462 : connection data from client NEVIN successfully processed

**Comment by hamiltra** [comment]
FTS_info.log ==> 
INFO : 2020-12-23 04:03:44,595 : Orchestrator.py:134 : client has connected
ERROR : 2020-12-23 04:03:44,602 : Orchestrator.py:159 : there has been an error in a clients connectionerror in the creation of client information
ERROR : 2020-12-23 04:03:44,605 : Orchestrator.py:469 : exception in receive connection data processing within main run function error in connection data processing data is -1
ERROR : 2020-12-23 05:11:44,862 : Orchestrator.py:305 : there has been an error in the reception of data in the monitoring of pipes B'int' object has no attribute 'type'
ERROR : 2020-12-23 05:11:44,867 : Orchestrator.py:469 : exception in receive connection data processing within main run function error in connection data processing data is -1
INFO : 2020-12-23 05:12:00,253 : Orchestrator.py:134 : client has connected
INFO : 2020-12-23 05:12:00,274 : Orchestrator.py:151 : finished establishing connectionWE6ACS
INFO : 2020-12-23 05:13:59,035 : Orchestrator.py:134 : client has connected
INFO : 2020-12-23 05:13:59,046 : Orchestrator.py:151 : finished establishing connectionNEVIN

**Comment by hamiltra** [comment]
The FTS_debug.log.4 shows when the issue began this AM ==>
ERROR : 2020-12-23 04:03:04,261 : Orchestrator.py:159 : there has been an error in a clients connectionerror in the creation of client information
ERROR : 2020-12-23 04:03:04,264 : Orchestrator.py:469 : exception in receive connection data processing within main run function error in connection data processing data is -1
INFO : 2020-12-23 04:03:44,595 : Orchestrator.py:134 : client has connected
ERROR : 2020-12-23 04:03:44,602 : Orchestrator.py:159 : there has been an error in a clients connectionerror in the creation of client information
ERROR : 2020-12-23 04:03:44,605 : Orchestrator.py:469 : exception in receive connection data processing within main run function error in connection data processing data is -1
ERROR : 2020-12-23 05:11:44,862 : Orchestrator.py:305 : there has been an error in the reception of data in the monitoring of pipes B'int' object has no attribute 'type'
ERROR : 2020-12-23 05:11:44,867 : Orchestrator.py:469 : exception in receive connection data processing within main run function error in connection data processing data is -1
INFO : 2020-12-23 05:12:00,253 : Orchestrator.py:134 : client has connected
INFO : 2020-12-23 05:12:00,274 : Orchestrator.py:151 : finished establishing connectionWE6ACS
DEBUG : 2020-12-23 05:12:00,292 : Orchestrator.py:462 : connection data from client <callsign> successfully processed
INFO : 2020-12-23 05:13:59,035 : Orchestrator.py:134 : client has connected
INFO : 2020-12-23 05:13:59,046 : Orchestrator.py:151 : finished establishing connectionNEVIN
DEBUG : 2020-12-23 05:13:59,056 : Orchestrator.py:462 : connection data from client NEVIN successfully processed

**Comment by naman108** [comment]
if there's an FTS_warning.log.1 there should also be a FTS_warning.log

**Comment by hamiltra** [comment]
I'm attaching the full logs for FTS_warning.log and FTS_warning.log.1 and my MainConfig.py. The sequence of events after the loss of server connection was to kill the server entirely using FreeTAK CLI and then perform a full restart of services. If I need to do a Zoom or Meet or something else to demonstrate, let me know. Since this is a dev server, I am happy to scrape FreeTAKServer and retest at anytime.


[FTS_warning.log](https://github.com/FreeTAKTeam/FreeTakServer/files/5736441/FTS_warning.log)
[freetaklogs.tar.gz](https://github.com/FreeTAKTeam/FreeTakServer/files/5736449/freetaklogs.tar.gz)

**Comment by naman108** [comment]
alright so this appears to be due to the certPaths being invalid and even though your not using ssl it's trying to start the services associated with SSL. so there are 2 solutions.
a) use -AutoStart False argument and start each service from the CLI
b) edit change your FTS.py to the following
[gitfxFTS.txt](https://github.com/FreeTAKTeam/FreeTakServer/files/5736484/gitfxFTS.txt)

PS. I removed your .tar.gz file as it contained your IP in the MainConfig.py

**Comment by hamiltra** [comment]
Thanks @naman108 . This will help a lot. I had wondered how the SSL was being handled without proper certs - now I know. I will incorporate these changes and retest immediately. Thanks for removing the tar file as it was a concern. I'll update this thread as soon as I know more about this issue.

**Comment by naman108** [comment]
excellent glad I could help we will also consider implementing an SSL on/off argument in the MainConfig.py as to streamline the process as a result of this so thank you aswell.

**Comment by hamiltra** [comment]
Ok, I restarted the server using method a) above. Retested that WinTak and ATAK clients played nicely which they did. Opened email client on WinTak machine and then started getting timeouts again. Server connection lost to both clients and never recovered after a few minutes. Logged into RPi, used client to kill server which said it worked in the interface.  Checking on the shell cli, server was still running. Manually killed all server threads, verified was killed and then restarted server again. Both clients now playing happily again. I'm wondering if communications are getting delayed to the server a little too long. Let me know when you're ready to receive logs which I'll collect.

**Comment by naman108** [comment]
possibly but I suspect the cause is the same could you first try method b

**Comment by hamiltra** [comment]
Trying method b.  Scraped all the logs, db, etc and installed the revised FTS.py file. I restarted the server on a private network:

python3 -m FreeTAKServer.controllers.services.FTS -DataPackageIP <ip> -AutoStart false -CoTIP <ip> -CoTPort 8087 -DataPackagePort 8080 > /home/rah/tak.log 2>&1 &

then started services:

python3 -m FreeTAKServer.views.CLI

Started WinTak and ATAK clients with a successful run of one hour with only one dropout which corrected itself on the next polling cycle. Let me repeat the same steps on the other network.

**Comment by hamiltra** [comment]
Tried method b on other network successfully. Potentially, method a is doing something unexpected. Unless there're further comments and other than the SSL actions mentioned, this could be closed and documented as an SSL setup issue.

**Comment by hamiltra** [comment]
I may have spoken too soon. Testing with Client 3 Asus ZenPad z8 started failing like before with method b. Client 3 and Client 1 (Moto z4) are on the same network as the server. Let me collect the logs and set aside for inspection.

**Comment by naman108** [comment]
Ok what was your startup command?

**Comment by hamiltra** [comment]
Same as 3 comments above with the IP filled in. The placeholder removed the placeholder.

**Comment by naman108** [comment]
ok for with method b) use the following startup command `python3 -m FreeTAKServer.controllers.services.FTS -DataPackageIP ipaddr -CoTIP ipaddr -CoTPort 8087 -DataPackagePort 8080 > /home/rah/tak.log 2>&1 &`

**Comment by hamiltra** [comment]
Using method b and the server startup command provided with ipaddr gives a Data reception timeout within 1-2 minutes. Load average on the RPi4 is very low (~0.25). Both clients used were ATAK clients on same network as FTS.

**Comment by naman108** [comment]
ok now could you try just running python3 -m FreeTAKServer.controllers.services.FTS > /home/rah/tak.log 2>&1 &

**Comment by hamiltra** [comment]
Getting intermittent connections to the server with Data reception timeout. Looks to consistently be the same behavior for method b.

**Comment by naman108** [comment]
what shows up in the /home/rah/tak.log

**Comment by hamiltra** [comment]
Log attached...

[tak.log](https://github.com/FreeTAKTeam/FreeTakServer/files/5740164/tak.log)

**Comment by naman108** [comment]
could you send the warning logs aswell also try setting the DataPackageServiceDefaultIP to '0.0.0.0' in the MainConfig

**Comment by hamiltra** [comment]
Here're the logs.  Will alter the config and rerun with the DP service change requested.

[method_b_logs_20201224_0800.tar.gz](https://github.com/FreeTAKTeam/FreeTakServer/files/5740233/method_b_logs_20201224_0800.tar.gz)

**Comment by hamiltra** [comment]
Repeated testing with change to MainConfig.py as requested and using the last server startup command requested above.  Same clients ATAK Moto z4 and Asus ZenPad and within 2 minutes get a Data reception timeout. Please advise if a debug build is required or additional logs needed.

**Comment by naman108** [comment]
ok I see the issue. somewhere on one of your clients you've specified an email which causes the connection to fail I believe this also causes issues with the DB, if it helps the issue is deffinitely not with the client with callsign NEVIN

**Comment by hamiltra** [comment]
I rechecked that client and I had forgotten that I had set those attributes on the Asus ATAK client. I selected publish phone number, removed xmpp name and preferred email. Restarted the server and tested for 10 minutes with no issues.

Apologies, the fault was my own as I should've caught that issue in my testing setup. I'll continue with testing when I can through this weekend and keep you advised of anything related to this issue if encountered. Thank you for the excellent support.

**Comment by naman108** [comment]
of course no problem at all best of luck once. If you have any further issues don't hesitate to open another issue in the meantime I'll leave this issue open and once you can confirm your FTS instance is working it would be greatly appreciated if you could close the issue.

**Comment by hamiltra** [comment]
Issue resolved. WinTAK and ATAK clients should not populate or publish phone numbers for the fields of VoIP, email and XMPP. Also, on WinTAK clients, unload the plugin TAKChat in the Plug-in Manager.
