### ISSUE TITLE
Server works for ~10 minutes, then stops

### ISSUE THREAD

**Issue by DavidBenKaplan** [FreeTAKTeam/FreeTakServer#106]
Running the server, it works great for 10 to 15 minutes, then stops responding to all devices.  On Android, ATAK shows the error "Data reception timeout, connection to host timed out".

The server is run using the command `sudo python3 -m FreeTAKServer.controllers.services.FTS -DataPackageIP 0.0.0.0 -AutoStart True`, and is running on an Ubuntu 20.04 LTS VPS.

Server version is 1.3.0.6.

The server executes normal for a while and outputs standard data (some details removed for privacy):
```
handling reg data
sending data to fts clientb'<event version="2.0" uid="takPong""
sending data to fts clientb'<event version="2.0" uid="takPong""
sending data to fts clientb'<event version="2.0" uid="takPong""
handling reg data
sending data to fts clientb'<event version="2.0" uid="takPong""
sending data to fts clientb'<event version="2.0" uid="takPong""
sending data to fts clientb'<event version="2.0" uid="takPong""
```
At this point, the two Android clients, and a WinTAK client all see each other.

Then, after a while, the server outputs:
```
(3840) accepted ('45.xx.yy.zz', 8609)
45.xx.yy.zz - - [23/Dec/2020 22:24:49] "GET /Marti/api/clientEndPoints HTTP/1.1" 200 162 0.005671
(3840) accepted ('45.xx.yy.zz', 3061)
45.xx.yy.zz - - [23/Dec/2020 22:24:49] "GET /Marti/api/version/config HTTP/1.1" 200 273 0.000678
(3840) accepted ('24.xx.yy.zz', 47550)
24.xx.yy.zz - - [23/Dec/2020 22:24:49] "GET /Marti/api/clientEndPoints HTTP/1.1" 200 162 0.000829
(3840) accepted ('24.xx.yy.zz', 47552)
24.xx.yy.zz - - [23/Dec/2020 22:24:49] "GET /Marti/api/version/config HTTP/1.1" 200 273 0.000887
(3840) accepted ('45.xx.yy.zz', 4473)
45.xx.yy.zz - - [23/Dec/2020 22:28:43] "GET /Marti/api/version/config HTTP/1.1" 200 273 0.004620
```

At this point, the all clients lose connection.

**Comment by alisterchapman** [comment]
I'm seeing the same behaviour. The server runs for about 20-30mins and then the clients lose the connection. This happens on two different Debian servers. Prior to upgrading to 1.3 RC6 the same servers ran reliably for weeks.

**Comment by lennisthemenace** [comment]
> I'm seeing the same behaviour. The server runs for about 20-30mins and then the clients lose the connection. This happens on two different Debian servers. Prior to upgrading to 1.3 RC6 the same servers ran reliably for weeks.

This is due to you not having certs on the server. you need to generate them and then it will stay up

**Comment by naman108** [comment]
@lennisthemenace has created a great tool for this which can be found at https://github.com/lennisthemenace/ATAK-Certs

**Comment by DavidBenKaplan** [comment]
Thank you @lennisthemenace and @naman108 !!!  Installed the certs, and the server has been running fine for > 90 minutes.
