### ISSUE TITLE
FTS 1.5 Failing to create Data Packages with the correct IP address

### ISSUE THREAD

**Issue by lennisthemenace** [FreeTAKTeam/FreeTakServer#109]
![image](https://user-images.githubusercontent.com/9608283/106047471-90e58f80-60db-11eb-9196-01acc78d7776.png)
![image](https://user-images.githubusercontent.com/9608283/106047501-98a53400-60db-11eb-8f72-600dcd90577b.png)
![image](https://user-images.githubusercontent.com/9608283/106047518-9e9b1500-60db-11eb-8cd9-1a023ee64f6e.png)
![image](https://user-images.githubusercontent.com/9608283/106047538-a3f85f80-60db-11eb-9430-76723cd98125.png)

**Comment by naman108** [comment]
UsserConnectionIP needs to be set in the MainConfig.py

**Comment by lennisthemenace** [comment]
so why would that then create one with an address of 127.0.1.1? and not 127.0.0.1 or 0.0.0.0,
If this is the case, then setting the ip in the UI is quite misleading

**Comment by naman108** [comment]
due to this line 
`    if MainConfig.UserConnectionIP == "0.0.0.0":
        hostname = socket.gethostname()
        server_address = socket.gethostbyname(hostname)
    else:
        server_address = MainConfig.UserConnectionIP`
lines 79-83 in the certificate_generation.py which is essentially just ATAKOfTheCerts wrapped into FTS

**Comment by lennisthemenace** [comment]
this is why i advised against doing this as that almost never returns usable address, and why i didnt add it into atakofthecerts

**Comment by naman108** [comment]
yup we didnt get around to removing it however I'll mark this as a bug and make sure it's removed before release however we have DataPackage IP and SSL connection package IP seperated so in future if the services are running seperately they aren't completely linked.

**Comment by lennisthemenace** [comment]
this obviously issnt something for here (more like discord) but running the DP services on different ips...is that even supported in atak?
but more UI configuration is always better :) even if users then decide to disable the ui after

**Comment by BobsBlueNorth** [comment]
I am on 2.2.1 and I still notice this issue. The certs generated for SSL connections always return with my LAN IP.
