### ISSUE TITLE
Overloaded Base Types

### ISSUE THREAD

**Issue by gregbuehler** [FreeTAKTeam/FreeTakServer#113]
In the base types enumeration `Attack`, `Medevac`, and `Medium` are repeated with different values. These should probably have distinct keys. 

https://github.com/FreeTAKTeam/FreeTakServer/blob/master/FreeTAKServer/model/RestMessages/RestEnumerations.py#L131

**Comment by brothercorvo** [comment]
thank you, this has been fixed (BTW, the original is coming from ATAK, so it's probably they have a similar bug
