### ISSUE TITLE
ssl delete cert and deny user who had previous access

### ISSUE THREAD

**Issue by jazap** [FreeTAKTeam/FreeTakServer#114]
**Feature request:**

Current setting:
If ssl server use required.
(1. send online users the cert by adding them to UI.
(2. close tcp port.
(3. at end of ssl use destroy the server (because deleting users at the UI and their certs in root/ does not deny them further ssl server access).

Feature request:
Is there a way to link deleting user at UI to also delete/deny user ssl access to the server?

**Comment by naman108** [comment]
not at the moment however I'll mark this as a feature

**Comment by brothercorvo** [comment]
added to the roadmap
