### ISSUE TITLE
Replay history on server.

### ISSUE THREAD

**Issue by almostik** [FreeTAKTeam/FreeTakServer#127]
Hi. It will be nice to have feature to use native Wintak Replay plugin to play some history from FTS.
Nice ability to analyze any gathering data and helpful in any kind of tests.

**Comment by naman108** [comment]
ya that's a really good point currently most CoT is being saved in the DB so before it's integrated in FTS maybe someone could read that DataBase information, serialize back into CoT and forward it.

**Comment by brothercorvo** [comment]
the features to 
Replay history on server
track movements. 
has been added to the roadmap
