### ISSUE TITLE
 RawCoT dbController missing

### ISSUE THREAD

**Issue by meulemans** [FreeTAKTeam/FreeTakServer#130]
SendCoTAbstractController.py has a reference to RawCoT.dbController.create_CoT(object.modelObject) on line 35 but there is no dbController defined in RawCoT.

https://github.com/FreeTAKTeam/FreeTakServer/blob/f5df8d9c7feea1162116d98b744438eca780a1ad/FreeTAKServer/controllers/SpecificCoTControllers/SendCoTAbstractController.py#L35

https://github.com/FreeTAKTeam/FreeTakServer/blob/45a2f5c86a322215e59c248d30faa14c812dcb94/FreeTAKServer/model/RawCoT.py#L12

**Comment by naman108** [comment]
though we should add an empty refrence in RawCoT the dbController attribute is defined here
https://github.com/FreeTAKTeam/FreeTakServer/blob/f5df8d9c7feea1162116d98b744438eca780a1ad/FreeTAKServer/controllers/services/Orchestrator.py#L198

**Comment by brothercorvo** [comment]
it's fixed ?
