### ISSUE TITLE
defusedxml SubElement error

### ISSUE THREAD

**Issue by meulemans** [FreeTAKTeam/FreeTakServer#131]
the use of defusedxml breaks this line, the SubElement call creates the following error:
exception filtering CoT Argument '_parent' has incorrect type (expected lxml.etree._Element, got xml.etree.ElementTree.Element)
https://github.com/FreeTAKTeam/FreeTakServer/blob/8fe8f3231fd1373de9c5e7ff4176058d4400e2b0/FreeTAKServer/controllers/SpecificCoTControllers/SendOtherController.py#L43

using from lxml import etree instead of from defusedxml import ElementTree as etree fixes the issue.

**Comment by naman108** [comment]
could you send an example of CoT which would fail?

**Comment by naman108** [comment]
fixed and tested with your CoT
