### ISSUE TITLE
Data Package are set to private by default

### ISSUE THREAD

**Issue by Clem103** [FreeTAKTeam/FreeTakServer#136]
After some testing using a (working) FTS 1.7.5, it seems that it is no longer possible to share anything involving Data Package from client to client (through the server).

From my understanding the expected behaviour should be :
-> User A tries to send an object (shape, picture, geofence, config and certs, ...) to User B 
-> a data package is created on the server (with public visibility) 
-> an url is sent to User B pointing to the corresponding DP 
-> DP is automaticaly retrieved by ATAK 
-> DP's visibility can be set to private after download (in the case of DP containing certs)

After discussing with crusty11b on discord the current behaviour appears to be : 
-> User A tries to send an object to User B
-> A DP is created (with private visibility)
-> URL is sent to User B but ATAK can't fibn the corresponding DP

To the best of my knowledge, it causes issues with sharing any kind of object (shapes, geofences, picture, ...) and also with DP generated by a user creation in the Web UI (on this specific point, issue is linked with #115)

**Comment by brothercorvo** [comment]
which client are you using?
it looks like the issue appears first in ATAK 4.3

**Comment by Clem103** [comment]
I use ATAK 4.3 on both phones I used for the test

**Comment by brothercorvo** [comment]
>-> URL is sent to User B but ATAK can't fibn the corresponding DP
in FTS you need to st your external IP (the one that is visible from the internet)  in the UI under Configure/Data Package IP
If you are not using UI you can set it in the mainconfig.py

**Comment by Clem103** [comment]
The IP was already set both on UI and mainconfig.py

**Comment by Clem103** [comment]
Tested with FTS 1.8 and ATAK 4.2.0, and the issue is still here

**Comment by brothercorvo** [comment]
please describe you issue better, we are able to send Data packages from user to user with no issue

**Comment by Clem103** [comment]
I'll try a fresh install with latest commit from Github. But for now, I can't be more specific on the issue than what I explained [here](https://github.com/FreeTAKTeam/FreeTakServer/issues/136#issue-869611955).

**Comment by brothercorvo** [comment]
![image](https://user-images.githubusercontent.com/60719165/119016289-239e8880-b970-11eb-9582-bdff7ed6a080.png)
from what you explain here, the issue is that you have not properly set the IP of the Data package server. Please try to install it properly, from what we can see this is not a bub

**Comment by Clem103** [comment]
I've done a fresh install, with correct config. 
I can send DP (inlcuding shapes) from one user to another, but the server still can't send a newly generated cert to a user. It used to work fine in 1.5
