### ISSUE TITLE
Tips for using this in third-party app

### ISSUE THREAD

**Issue by geospatialmapmashup** [FreeTAKTeam/FreeTakServer#137]
We are interested in integrating with FreeTAK Server for GeoNames Map Explorer iOS and Android http://geonamesmapexplorer.xyz
I don't have a problem reading documentation and reviewing API endpoints
but I wanted to know if you had any tips or recommendations for integration

We've been contacted by some users to add support for this capability and it seems like a great idea.
maps@techmaven.net

**Comment by brothercorvo** [comment]
It depends from the type of integration you intent to create. If your app works like a full TAK client, then you should use a TCP connection and XML.
If you are looking for a non continous transfer of data, then you should use the REST API
