### ISSUE TITLE
Instructions about Building FTS source code in Visual Studio Code?

### ISSUE THREAD

**Issue by combat-networks** [FreeTAKTeam/FreeTakServer#142]
How can I build FTS in Visual Studio Code after I git the source code from Github?

**Comment by naman108** [comment]
> How can I build FTS in Visual Studio Code after I git the source code from Github?

everything should work OOTB as long as you've added the dependancies

**Comment by naman108** [comment]
@brothercorvo can we close this?

**Comment by brothercorvo** [comment]
Coding as completed
