### ISSUE TITLE
Webmap Server + (zoom in) button doesn't allow click

### ISSUE THREAD

**Issue by john0sweet** [FreeTAKTeam/FreeTakServer#146]
Using Firefox 78.8 from Debian, unable to trigger an action when clicking on zoom in button in webmap on FTS 1.8. Cursor changes to " pointed finger" just to right hand side of + button (for width approx 10 pixels) but clicking results in no action. Link "JavaScript:void(0)" appears in bottom left of window.
"-" button functions normally most of the time, with occasionally detection failures.

(1.8 looking good so far, good job!)

**Comment by john0sweet** [comment]
Ps to add - scroll wheel zoom on mouse functions normally

**Comment by naman108** [comment]
good find, will address in 1.8.1 thank you

**Comment by naman108** [comment]
fixed in 1.8.1
