### ISSUE TITLE
FTS 1.7.5 wait CPU issue appears to still be active in 1.8

### ISSUE THREAD

**Issue by skadakar** [FreeTAKTeam/FreeTakServer#149]
Ugly workaround:
sed -e '603i\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ time.sleep(0.01)' -i /usr/local/lib/python3.8/dist-packages/FreeTAKServer/controllers/services/FTS.py

**Comment by naman108** [comment]
fixed in 1.8.1
