### ISSUE TITLE
Regeneration of user data package

### ISSUE THREAD

**Issue by lennisthemenace** [FreeTAKTeam/FreeTakServer#156]
If you have user certs configured and on the server through the ui. Then you change the ip address to the server, the data packages will no longer point to the correct address. 

Can there be a button to regenerate a users certs package?

**Comment by naman108** [comment]
that's a good idea I'll mark this as a 1.9 enhancment.

**Comment by naman108** [comment]
this will require the addition of a new button to the UI and possibly a new endpoint for the api

**Comment by brothercorvo** [comment]
for now the best approach is to delete the user, that is also the same we do when certs are not valid.
