### ISSUE TITLE
FTS REST API method PUT

### ISSUE THREAD

**Issue by niccellular** [FreeTAKTeam/FreeTakServer#163]
While testing an app that interfaces with FTS via the REST API the behavior of the PUT method did not appear to work as intended.

Using the /ManageGeoObject/putGeoObject endpoint to update a CoT with a valid uid returned from FTS from a previous POST resulted the original displayed GeoObject was deleted and never updated on the EUD.

If  the postGeoObject endpoint is used instead with a valid uid returned from the server from a previous POST the CoT is correctly updated on the EUD as expected.

**Comment by naman108** [comment]
I was not able to reproduce could you send your OS, the CoT message and your FTS version?
