### ISSUE TITLE
TypeError: cannot pickle 'SSLSocket'object

### ISSUE THREAD

**Issue by howied231** [FreeTAKTeam/FreeTakServer#164]
I get the above error in the FTS console about once a minute and it causes the ATAK connection to drop for about 30 seconds when connected using SSL.

<FreeTAKServer.model.FTSModel.Chatgrp.Chatgrp object at 0x7f008e3bedc0>
Traceback (most recent call last):
File "/usr/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
obj = _ForkingPickler.dumps(obj)
File "/usr/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
cls(buf, protocol).dump(obj)
File "/usr/lib/python3.8/socket.py", line 272, in __getstate__
raise TypeError(f"cannot pickle {self.__class__.__name__!r} object")
TypeError: cannot pickle 'SSLSocket' object

It appears to be similar to the errors described here:

[https://stackoverflow.com/questions/8804830/python-multiprocessing-picklingerror-cant-pickle-type-function](url)

I have FTS 1.8.1 installed on a clean instance of Ubuntu 20.04.2

**Comment by naman108** [comment]
thank you, we're working to fix this in 1.9

**Comment by DRKolev-code** [comment]
Hi, I hate to reopen this but how did you solve the issue? Could you point me to the code that makes it possible to pickle SSLSocket?

**Comment by howied231** [comment]
I don’t think I did. If I remember correctly this was an issue when I was trying to get the code to run under Centos 7. I finally gave up on that idea.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by brothercorvo** [comment]
the issue has been addressed by changing the way we handle the socket.
