### ISSUE TITLE
Installing of FTS failed

### ISSUE THREAD

**Issue by Orodreth87** [FreeTAKTeam/FreeTakServer#165]
Hi there,
i tried u install the FTS Server on Windows 10.
When u i use the command flask run i get this error.

May somebody can help me?

Thanks guys.

> F:\python\Lib\site-packages\FreeTAKServer-UI>flask run
>  * Serving Flask app "run.py"
>  * Environment: production
>    WARNING: This is a development server. Do not use it in a production deployment.
>    Use a production WSGI server instead.
>  * Debug mode: off
> Usage: flask run [OPTIONS]
> Try 'flask run --help' for help.
> 
> Error: While importing "FreeTAKServer-UI.run", an ImportError was raised:
> 
> Traceback (most recent call last):
>   File "f:\python\lib\site-packages\flask\cli.py", line 240, in locate_app
>     __import__(module_name)
>   File "F:\python\Lib\site-packages\FreeTAKServer-UI\run.py", line 38, in <module>
>     from config import config_dict
> ModuleNotFoundError: No module named 'config'

**Comment by Cale-Torino** [comment]
@Orodreth87  Try running in your app folder then run in the UI folder again.

> try run in `F:\python\Lib\site-packages\FreeTAKServer-UI\app` folder
> 
> delete `__ini__.py` 0kb file in `F:\python\Lib\site-packages\FreeTAKServer-UI`
> 
> then try run in `F:\python\Lib\site-packages\FreeTAKServer-UI` folder
> 
> pip install requests

A better solution would be to use [Docker ](https://www.docker.com/products/docker-desktop)for windows 10...

The complicated windows install method works but it's very easy to make a mistake. Also it was designed as an alternative install. For example `Windows 2012` which does not support Docker has no other way except VM or the long tutorial.

**Comment by brothercorvo** [comment]
@Orodreth87 have you fixed your issue?
