### ISSUE TITLE
windows install - ModuleNotFound Error when running 'flask'

### ISSUE THREAD

**Issue by b1uebu11** [FreeTAKTeam/FreeTakServer#169]
Wrote this up on [stackoverflow](https://stackoverflow.com/questions/68060604/i-get-this-error-when-executing-flask-run-modulenotfounderror-no-module-name) - attempted a re-install, still seeing the same error.

^**This question on stackoverflow has since closed**

-----------------------------------------------------------------

Below is what I wrote up on the issue I'm experiencing, still.

I am using this guide to build a FreeTAKServer on a windows machine with Python3. When running this code:

set FLASK_APP=run.py
flask run
I receive this result and the server won't run:

 * Serving Flask app "run.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing "FreeTAKServer-UI.run", an ImportError was raised:

Traceback (most recent call last):
  File "c:\software\python\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
  File "C:\Software\python\Lib\site-packages\FreeTAKServer-UI\run.py", line 38, in <module>
    from config import config_dict
ModuleNotFoundError: No module named 'config'

-----------------------------------------------------------------

I've attached screengrabs below of;
1. cli.py - line 240
2. desired result example
3. flask debug results
4. run.py - line 38
5. what I originally posted on stackoverflow

-----------------------------------------------------------------

![cli py_line 240](https://user-images.githubusercontent.com/86221991/125407865-a5091900-e3fd-11eb-8027-79a4513f85ac.PNG)
![desired result - flask run](https://user-images.githubusercontent.com/86221991/125407868-a5a1af80-e3fd-11eb-82c1-fc3ac8eb06fb.PNG)
![flask debug](https://user-images.githubusercontent.com/86221991/125407873-a6d2dc80-e3fd-11eb-9085-b9425f2f7ae6.PNG)
![run py_line 38](https://user-images.githubusercontent.com/86221991/125407876-a6d2dc80-e3fd-11eb-90ae-2abe4874763d.PNG)
![stackoverflow - flask run question - now closed - FTS](https://user-images.githubusercontent.com/86221991/125407878-a76b7300-e3fd-11eb-8ede-dd4b3159c8b0.PNG)

**Comment by brothercorvo** [comment]
use pip to install Flask.
Laso follow the docs for windows
https://freetakteam.github.io/FreeTAKServer-User-Docs/Installation/Windows/FreeTAKServer_Windows_Install.html

**Comment by b1uebu11** [comment]
Hey borthercorvo, I installed Flask using pip as per the instructions in the guide, however I still can't successfully run the UI. Since my question on stackoverflow was auto-closed, I've edited my original comment above to dump what I raised on stackoverflow.

Any thoughts?

Cheers

**Comment by Cale-Torino** [comment]
@b1uebu11 It looks like the server is running fine but your UI has a problem.

 I had this problem before... follow this to quick fix:

> try run in F:\python\Lib\site-packages\FreeTAKServer-UI\app folder
> 
> delete __ini__.py 0kb file in F:\python\Lib\site-packages\FreeTAKServer-UI
> 
> then try run in F:\python\Lib\site-packages\FreeTAKServer-UI folder
> 
> pip install requests

Afterwards try run the UI again.

**Comment by b1uebu11** [comment]
Hey @Cale-Torino, I followed your steps, got it running! However, now I'm receiving an internal server error haha, does this mean I have a break in the connection to the database?

Posted results when hitting the localhost from a browser below:


[Error log when accessing localhost.txt](https://github.com/FreeTAKTeam/FreeTakServer/files/6812120/Error.log.when.accessing.localhost.txt)

**Comment by ElSteveGrande** [comment]
I had the same thing happen. When I uncommented     

`SQLALCHEMY_DATABASE_URI = 'sqlite:///:memory:'`

Things started "working" but the pages were very slow to load and it didn't seem like it was working (although it was not spitting errors anymore).
