### ISSUE TITLE
RestAPI 2.0

### ISSUE THREAD

**Issue by brothercorvo** [FreeTAKTeam/FreeTakServer#177]
Rewrite the APi as component, describe the API as an OpenAPI

**Comment by HeroesLament** [comment]
Tasks remaining: 
1. Convert Postman v2.1 to OpenAPI 2.0 spec
2. Add descriptions + Lorem Ipsums for endoints and verbs

**Comment by brothercorvo** [comment]
Open API has been committed to 
https://github.com/FreeTAKTeam/FreeTAKTest/tree/main/TestData/OpenAPIschema
closing this
