### ISSUE TITLE
Installation documentation/ scripting error (linux)

### ISSUE THREAD

**Issue by cgriffin315** [FreeTAKTeam/FreeTakServer#186]
After following installation guide for linux, the installation either does not point to the correct directory or the installation does not create the necessary directories. Currently working with 1.9.1.5 with ui. 

![Run Freetak error](https://user-images.githubusercontent.com/56194148/127728112-34a504f4-0bf1-4a63-bece-136be66400cb.PNG)

**Comment by naman108** [comment]
upgrade to python version 3.8 and try again

**Comment by AnT1ThesIs** [comment]
No dice, upgrade to 3.8, made sure the libxml2-dev and libxslt-dev was installed for the install to complete successfully. Same error is coming up.

**Comment by naman108** [comment]
can you send a screenshot because if the error message is the exact same then you arent running the command with python3.8

**Comment by AnT1ThesIs** [comment]
It was running with 3.8, switching to Ubuntu server fixed the issue. For now there is something wrong with installing with PiOS.
