### ISSUE TITLE
1.9: REST API: postPresence error 500 on certain team colors

### ISSUE THREAD

**Issue by sgofferj** [FreeTAKTeam/FreeTakServer#189]
When using the following team colors in a postPresence request, the REST API returns an error 500:
- Orange
- Magenta
- Maroon
- Purple
- Dark Blue
- Teal
- Dark Green
- Brown

Checked with WebUI and own application. Nothing relevant seem to be looged in any of the log files.

**Comment by sgofferj** [comment]
Same goes for role "Team Leader" in a color where "Team Member" works.

**Comment by naman108** [comment]
I will try to replicate this
