### ISSUE TITLE
FreeTAKServer Install Error

### ISSUE THREAD

**Issue by homefall** [FreeTAKTeam/FreeTakServer#192]
getting the following error when trying to install on a clean instance of Debian 11 following setup instructions:

```
prospectfire@prospectfiretak:~$ sudo python3 -m FreeTAKServer.controllers.services.FTS 
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/FreeTAKServer/controllers/services/FTS.py", line 6, in <module>
    from FreeTAKServer.controllers.services.TCPDataPackageService import TCPDataPackageService as TCPFlaskFunctions
  File "/usr/local/lib/python3.9/dist-packages/FreeTAKServer/controllers/services/TCPDataPackageService.py", line 1, in <module>
    from .DataPackageServer import FlaskFunctions, Path, dp_directory, os, app, eventlet, const
  File "/usr/local/lib/python3.9/dist-packages/FreeTAKServer/controllers/services/DataPackageServer.py", line 50, in <module>
    os.mkdir(MainConfig.ExCheckMainPath)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/FreeTAKServer/ExCheck'
```
Any idea what is needed to resolve this?

**Comment by naman108** [comment]
the simplest way is to downgrade to python 3.8, alternatively you can set the MainPath to /usr/local/lib/python3.9/dist-packages/FreeTAKServer in the configuration at /opt/FTSConfig.yaml

**Comment by homefall** [comment]
Thank you for the quick response.  So I managed to downgrade python to 3.8.2 with a little poking around.  Now I am getting an error that it didn't install an SSL module.  Sorry but I am very green at dealing with python.  Was there a flag I needed to modify in the files I downloaded for 3.8.2 before I compiled and installed it?  Below is the output I received:
```
Collecting FreeTAKServer[ui]
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/freetakserver/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/freetakserver/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/freetakserver/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/freetakserver/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/freetakserver/
  Could not fetch URL https://pypi.org/simple/freetakserver/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/freetakserver/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  ERROR: Could not find a version that satisfies the requirement FreeTAKServer[ui] (from versions: none)
ERROR: No matching distribution found for FreeTAKServer[ui]
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

```

**Comment by homefall** [comment]
So i got the install to proceed after installing 3.8.2 over the top of the included python and then doing the following so that SSL would work with my 3.8.2 build

sudo apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget
then re-run the ./configure --enable-optimizations and make install steps

**Comment by guitarpicva** [comment]
> 
> 
> the simplest way is to downgrade to python 3.8, alternatively you can set the MainPath to /usr/local/lib/python3.9/dist-packages/FreeTAKServer in the configuration at /opt/FTSConfig.yaml

The simplest way is actually to adjust the base python version as noted above by changing the paths in a few places.  Also check the UI's config.py and the MainConfig.py.  Even though you may be using the yaml, if anything unusual happens, it will revert to these files.

Python 3.9 seems to work fine with FTS 1.9.1 on x64 Linux (Ubuntu 21.04).  I never like to downgrade, particularly system packages.

**Comment by AnT1ThesIs** [comment]
Use Ubuntu server, I was able to get it installed on 21.04 with 3.8. Now on to my SSL issues.

**Comment by naman108** [comment]
ok and can you send the output of running sudo python3?

**Comment by homefall** [comment]
Sure thing, thanks for the help
![image](https://user-images.githubusercontent.com/89408878/131289566-422d9a60-3def-4ffb-ab7b-8401aaedddf7.png)

**Comment by homefall** [comment]
So I guess we can mark this closed... I have abandoned this install of debian and moved to the mentioned Ubuntu 20.04 server.  Have the server MOSTLY working now but getting odd errors when trying to connect clients via TCP or SSL.  Assume you would prefer start a new item for these issues OR join the apparently similar thread on server disconnects.

**Comment by guitarpicva** [comment]
did you try to change the python path in the config files?  It works swimmingly here with Ubuntu 21.04 which uses python 3.9.

**Comment by NullVibes** [comment]
I've run into the same roadblock with Python versions.  The _/opt/FTSConfig.yaml_ file does not (yet) exist.  Can you specify the locations of where to fix the config to reflect Python version _3.9_?

**Comment by guitarpicva** [comment]
the yaml doesn't exist unless you create it AFAIK

both of the two main config files have Python environment variables to adjust, see above, Aug. 24 post.

**Comment by NullVibes** [comment]
**(Solved)**
Path:  _/usr/local/lib/python3.9/dist-packages/FreeTAKServer/controllers/configuration/_
File:   Edit MainConfig.py, Line #18 to reflect your version of Python.
   _python_version = 'python 3.9'_
