### ISSUE TITLE
newline character at end of RawCoT causes issues

### ISSUE THREAD

**Issue by dlwalter** [FreeTAKTeam/FreeTakServer#195]
I was working on a custom application where I was generating an XML CoT using QT's QXmlStreamWriter.  This Application runs on a Desktop and streams CoT messages to the server at a 2 second interval.  Then I use an android tablet running ATAK to view the friendly contact's position.

Using QT's documentation ending the XML Stream with
`QXmlStreamWriter::writeEndDocument()` (to close out the `writeStartDocument()`) adds a newline at the end of the XML.

On the server, the RawCoT.xmlString appears as:
```
[<?xml version="1.0" encoding="UTF-8" standalone="yes"?><event version="2.0" uid="MYCOT0" time="2021-08-25T00:15:32Z" start="2021-08-25T00:15:32Z" stale="2021-08-25T00:16:32Z" how="m-g" type="a-f-A"><point lat="34.0" lon="-118.0" hae="50" ce="9999999.0" le="9999999.0"/><detail><contact endpoint="*:-1:stcp" callsign="MYCOT"/><precisionlocation altsrc="GPS" geopointsrc="GPS"/><__group role="Team Member" name="Cyan"/><takv os="1" platform="qgc" version="1.0"/></detail></event>
]
```

This CoT then doesn't update correctly on the clients.  It stays in one position and bounces if the lat/lon changes.

Removing the `QXmlStreamWriter::writeEndDocument()` results in 
```
[<?xml version="1.0" encoding="UTF-8" standalone="yes"?><event version="2.0" uid="MYCOT0" time="2021-08-25T00:15:32Z" start="2021-08-25T00:15:32Z" stale="2021-08-25T00:16:32Z" how="m-g" type="a-f-A"><point lat="34.0" lon="-118.0" hae="50" ce="9999999.0" le="9999999.0"/><detail><contact endpoint="*:-1:stcp" callsign="MYCOT"/><precisionlocation altsrc="GPS" geopointsrc="GPS"/><__group role="Team Member" name="Cyan"/><takv os="1" platform="qgc" version="1.0"/></detail></event>]
```

With no newline at the end.  This CoT message updates on my android ATAK client and everything looks correct.

**Comment by guitarpicva** [comment]
Qt's methodology makes sense if you are writing a file on the file system or into a UI element such as QTextDocument or derivatives.  So it's a simple workaround to trim the QString.

Interesting catch. Thanks for the heads up.

**Comment by guitarpicva** [comment]
To add a bit more detail re: the server side transmission of line ends:

The following is FROM the FTS to the connecting client.  It seems the only time the <?xml...?> header is sent is then, and before each CoT for the connected clients.  Note that there is a line feed (0x0a) after the <?xml...."yes"?>  each time it is sent.  At the end of the following <event> tag there is NO line feed.  It is immediately followed by another <?xml....?>\n<event ....></event>

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<event version="2.0" uid="ANDROID-abea0bf660ff0887" type="a-f-G-U-C" time="2021-08-25T13:27:06.029Z" start="2021-08-25T13:27:06.029Z" stale="2021-08-25T13:33:21.029Z" how="m-g"><point lat="36.951976" lon="-77.674631" hae="61.685" ce="12.5" le="9999999.0"/><detail><takv os="30" version="4.4.0.RC (156bdcd1).1627326891-CIV" device="MOTOROLA MOTO G POWER" platform="ATAK-CIV"/><contact endpoint="*:-1:stcp" callsign="LINCHPIN6"/><uid Droid="LINCHPIN6"/><precisionlocation altsrc="GPS" geopointsrc="GPS"/><__group role="Team Member" name="Cyan"/><status battery="97"/><track course="208.60000610351562" speed="0.0"/></detail></event><?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<event version="2.0" uid="ANDROID-4e4ea2f158e84440" type="a-f-G-U-C" time="2021-08-25T13:27:19.491Z" start="2021-08-25T13:27:19.491Z" stale="2021-08-25T13:28:04.491Z" how="h-e"><point lat="37.0126688" lon="-77.1431639" hae="-7.327" ce="9999999.0" le="9999999.0"/><detail><takv os="29" version="4.4.0.3 (521e5e95).1629028772-CIV" device="MOTOROLA MOTO G(7) POWER" platform="ATAK-CIV"/><contact endpoint="*:-1:stcp" phone="8048950870" callsign="LINCHPINa"/><uid Droid="LINCHPINa"/><precisionlocation altsrc="DTED0"/><__group role="Team Member" name="Cyan"/><status battery="87"/><track course="335.8588507156234" speed="0.0"/></detail></event>
```

**Comment by dlwalter** [comment]
Thanks, for the info.

I was under the expectation that TAK would ignore [insignificant whitespace](https://www.liquid-technologies.com/XML/Whitespace.aspx) for any XML string.  Is this correct?

**Comment by brothercorvo** [comment]
> Thanks, for the info.
> 
> I was under the expectation that TAK would ignore [insignificant whitespace](https://www.liquid-technologies.com/XML/Whitespace.aspx) for any XML string. Is this correct?

no, this is not correct

**Comment by dlwalter** [comment]
@brothercorvo can you point me to a reference so I can understand how TAK needs the XML string formatted so I can avoid trial and error in the future?

**Comment by guitarpicva** [comment]
Have a look in the source for Atak in commoncommo

https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/blob/master/commoncommo/core/impl/protobuf/protocol.txt

I think you'll see the expected format of the XML in that file.

**Comment by dlwalter** [comment]
Perfect. Thank you.

**Comment by brothercorvo** [comment]
We do not suggest to use the XML for integration. use the REST API
