### ISSUE TITLE
How to install FreeTakServer from source code

### ISSUE THREAD

**Issue by nghiajenius-dev** [FreeTAKTeam/FreeTakServer#197]
Hi everyone, 

Is there a way to install FreeTAKServer and the WebUI from source code instead of installing via pip package?  Is there any installer script or instruction that I can follow?

Thanks and best,
Nghia.

**Comment by guitarpicva** [comment]
Yes, follow:

https://github.com/lennisthemenace/FreeTAKServer-Installer

I cannot vouch for it's quality but I did use the script to learn how to install the WebMaps.  Worth a look

**Comment by brothercorvo** [comment]
issue closed
