### ISSUE TITLE
REST API: PutGeoObject not working

### ISSUE THREAD

**Issue by brothercorvo** [FreeTAKTeam/FreeTakServer#200]
ManageGeoObject/putGeoObject
returns  405 METHOD NOT ALLOWED

![image](https://user-images.githubusercontent.com/60719165/139672404-c82cdf87-b1c0-4a2a-98f1-a1bb948b3194.png)

**Comment by naman108** [comment]
are you using a PUT request?

**Comment by brothercorvo** [comment]
additional testing on PUB 1.9.5 beta shows the following:

![image](https://user-images.githubusercontent.com/60719165/141688001-62fd0d95-4e59-412e-9b62-5a2d6979d1c9.png)

-  put returns a UID but on the API client, 
- However the COT simply disappears when updated in WIntak
- I can still correctly update the COT using the post method

**Comment by brothercorvo** [comment]
issue partially fixed. 
new test shows the following:
position is correctly updated. However, if the name is not sent again, the COT changes name to be equal UID

original COT
![image](https://user-images.githubusercontent.com/60719165/142645269-84d04afb-2ce2-40ac-90a3-5c297f6ff9f7.png)

message
```
{
"uid": "061dcf30-455e-11ec-8372-4e58de281c19",
"longitude": -77.0174,
"latitude": 38.889,
"attitude": "hostile",
"geoObject": "Sniper"
}
``
result after PUT 
![image](https://user-images.githubusercontent.com/60719165/142645383-cda3cbb4-44f8-459a-8c47-6b8c90938e56.png)

this can be fixed by always sending the name is the PUT, however it makes more difficult to automate COTS updates
```
{
"uid": "061dcf30-455e-11ec-8372-4e58de281c19",
"longitude": -77.0174,
"latitude": 38.889,
"attitude": "friendly",
"name": "Putin",
"geoObject": "Sniper"
}
```
