### ISSUE TITLE
something is wrong with my corrections to files or something.

### ISSUE THREAD

**Issue by HoneyBadgerActual** [FreeTAKTeam/FreeTakServer#211]
okay i had to edit this issue. i figured out WHY my UI wasnt working, my server isnt installed correctly. i wiped my termux clean and repeated the steps that worked and excluded all my experimenting steps that didnt.

my environment for install is this:
OS android 10 - not rooted
running Termux emulator from Fdroid

my relevent packages installed.

python
Version: 3.10.0-4
Maintainer: @termux
Installed-Size: 49.3 MB
Provides: python3
Depends: gdbm, libandroid-support, libbz2, libcrypt, libexpat, libffi, liblzma, libsqlite, ncurses, ncurses-ui-libs, openssl, readline, zlib
Recommends: clang, make, pkg-config
Suggests: python-tkinter
Breaks: python2 (<= 2.7.15), python-dev
Replaces: python-dev
Homepage: https://python.org/
Download-Size: 8326 kB
APT-Manual-Installed: yes
APT-Sources: https://packages.termux.org/apt/termux-main stable/main aarch64 Packages

pip
Version: 21.3.1
Summary: The PyPA recommended tool for installing Python packages.
Home-page: https://pip.pypa.io/
Author: The pip developers
Author-email: distutils-sig@python.org
License: MIT
Location: /data/data/com.termux/files/usr/lib/python3.10/site-packages

wheel
Version: 0.37.0
Summary: A built-package format for Python
Home-page: https://github.com/pypa/wheel
Author: Daniel Holth
Author-email: dholth@fastmail.fm
License: MIT
Location: /data/data/com.termux/files/usr/lib/python3.10/site-packages

eventlet
Version: 0.33.0
Summary: Highly concurrent networking library
Home-page: http://eventlet.net
Author: Linden Lab
Author-email: eventletdev@lists.secondlife.com
License: UNKNOWN
Location: /data/data/com.termux/files/usr/lib/python3.10/site-packages

libpath
Version: 0.0.0.0
Summary: libpath, for Python
Home-page: https://github.com/synesissoftware/libpath.Python
Author: Matt Wilson
Author-email: matthew@synesis.com.au
License: BSD-3-Clause
Location: /data/data/com.termux/files/usr/lib/python3.10/site-packages

SQLAlchemy                                              Version: 1.3.23                                               Summary: Database Abstraction Library
Home-page: http://www.sqlalchemy.org
Author: Mike Bayer                                            Author-email: mike_mp@zzzcomputing.com
License: MIT
Location: /data/data/com.termux/files/usr/lib/python3.10/site-packages

The problem i am having, and the unsolveable issue i can't seem to get around.

so when running this command i get this output.

pip install FreeTakServer==1.9.1
Collecting FreeTakServer==1.9.1                                 Using cached FreeTAKServer-1.9.1-py3-none-any.whl (323 kB)  Collecting sqlalchemy==1.3.20
  Using cached SQLAlchemy-1.3.20.tar.gz (6.3 MB)
  Preparing metadata (setup.py) ... done                      Collecting flask-httpauth==4.2.0
  Using cached Flask_HTTPAuth-4.2.0-py2.py3-none-any.whl (5.9 kB)                                                           Collecting PyYAML
  Using cached PyYAML-6.0-cp310-cp310-linux_aarch64.whl
Collecting python-engineio==3.13.2                              Using cached python_engineio-3.13.2-py2.py3-none-any.whl (50 kB)
Collecting pykml                                                Using cached pykml-0.2.0-py3-none-any.whl (41 kB)
Collecting lxml==4.6.1
  Using cached lxml-4.6.1.tar.gz (3.2 MB)                       Preparing metadata (setup.py) ... done
Collecting tabulate==0.8.7
  Using cached tabulate-0.8.7-py3-none-any.whl (24 kB)
Collecting psutil
  Using cached psutil-5.8.0-cp310-cp310-linux_aarch64.whl
Collecting geopy                                                Using cached geopy-2.2.0-py3-none-any.whl (118 kB)
Collecting protobuf==3.14.0
  Using cached protobuf-3.14.0-py2.py3-none-any.whl (173 kB)
Collecting python-socketio==4.6.0
  Using cached python_socketio-4.6.0-py2.py3-none-any.whl (51 kB)
Collecting flask-socketio==4.3.1
  Using cached Flask_SocketIO-4.3.1-py2.py3-none-any.whl (15 kB)
Collecting Jinja2==2.11.2
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Requirement already satisfied: setuptools in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from FreeTakServer==1.9.1) (57.4.0)
Collecting ruamel.yaml
  Using cached ruamel.yaml-0.17.17-py3-none-any.whl (109 kB)
Collecting pathlib==1.0.1
  Using cached pathlib-1.0.1.tar.gz (49 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /data/data/com.termux/files/usr/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-2acr585y/pathlib_fbe0e4a947b54b2db566c630ed8cf48d/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-2acr585y/pathlib_fbe0e4a947b54b2db566c630ed8cf48d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /data/data/com.termux/files/usr/tmp/pip-pip-egg-info-4lxuw3hg
       cwd: /data/data/com.termux/files/usr/tmp/pip-install-2acr585y/pathlib_fbe0e4a947b54b2db566c630ed8cf48d/
  Complete output (13 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 16, in <module>
      import setuptools.version
    File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/setuptools/version.py", line 1, in <module>
      import pkg_resources
    File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 23, in <module>
      import zipfile
    File "/data/data/com.termux/files/usr/lib/python3.10/zipfile.py", line 19, in <module>
      import pathlib
    File "/data/data/com.termux/files/usr/tmp/pip-install-2acr585y/pathlib_fbe0e4a947b54b2db566c630ed8cf48d/pathlib.py", line 10, in <module>
      from collections import Sequence
  ImportError: cannot import name 'Sequence' from 'collections' (/data/data/com.termux/files/usr/lib/python3.10/collections/__init__.py)
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ac/aa/9b065a76b9af472437a0059f77e8f962fe350438b927cb80184c32f075eb/pathlib-1.0.1.tar.gz#sha256=6940718dfc3eff4258203ad5021090933e5c04707d5ca8cc9e73c94a7894ea9f (from https://pypi.org/simple/pathlib/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pathlib==1.0.1 (from freetakserver) (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.97, 1.0, 1.0.1)
ERROR: No matching distribution found for pathlib==1.0.1

which i realize means that my pathlib seems to be all jacked up in termux right?

so the solution should be 

"pip install libpath==1.0.1" correct?

Except i get this output.

pip install pathlib==1.0.1
Collecting pathlib==1.0.1                                       Using cached pathlib-1.0.1.tar.gz (49 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:                 command: /data/data/com.termux/files/usr/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-90fu4n6m/pathlib_6e61d8fdbf104262be07649337e736ad/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-90fu4n6m/pathlib_6e61d8fdbf104262be07649337e736ad/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /data/data/com.termux/files/usr/tmp/pip-pip-egg-info-pvkz4us6                                                    cwd: /data/data/com.termux/files/usr/tmp/pip-install-90fu4n6m/pathlib_6e61d8fdbf104262be07649337e736ad/                Complete output (13 lines):                                   Traceback (most recent call last):
    File "<string>", line 1, in <module>                          File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 16, in <module>
      import setuptools.version
    File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/setuptools/version.py", line 1, in <module>
      import pkg_resources
    File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 23, in <module>
      import zipfile
    File "/data/data/com.termux/files/usr/lib/python3.10/zipfile.py", line 19, in <module>
      import pathlib
    File "/data/data/com.termux/files/usr/tmp/pip-install-90fu4n6m/pathlib_6e61d8fdbf104262be07649337e736ad/pathlib.py", line 10, in <module>
      from collections import Sequence
  ImportError: cannot import name 'Sequence' from 'collections' (/data/data/com.termux/files/usr/lib/python3.10/collections/__init__.py)
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ac/aa/9b065a76b9af472437a0059f77e8f962fe350438b927cb80184c32f075eb/pathlib-1.0.1.tar.gz#sha256=6940718dfc3eff4258203ad5021090933e5c04707d5ca8cc9e73c94a7894ea9f (from https://pypi.org/simple/pathlib/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pathlib==1.0.1 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.97, 1.0, 1.0.1)
ERROR: No matching distribution found for pathlib==1.0.1

or maybe the solutiom is the pkg command?

lets try:

pkg install pathlib==1.0.1 

pkg install pathlib==1.0.1
Checking availability of current mirror: ok
Get:1 https://packages.termux.org/apt/termux-main stable InRelease [14.0 kB]
Hit:2 https://packages.termux.org/apt/termux-games games InRelease
Hit:3 https://packages.termux.org/apt/termux-science science InRelease
Hit:4 https://packages.termux.org/apt/termux-x11 x11 InRelease
Get:5 https://packages.termux.org/apt/termux-main stable/main aarch64 Packages [282 kB]
Fetched 296 kB in 7s (45.3 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package pathlib=

So that was a no go, ive tried the same or similar commands with multiple package installers...

whats my solution here? anyone?

**Comment by brothercorvo** [comment]
OS android 10 running Termux emulator from Fdroid is a not supported environment. To run FTS on ANdroid you should use FTS 1.6 Android edition that is a native Android application

**Comment by HoneyBadgerActual** [comment]
> OS android 10 running Termux emulator from Fdroid is a not supported environment. To run FTS on ANdroid you should use FTS 1.6 Android edition that is a native Android application

I cant seem to get the UI version for android to work.
I've followed the entire page to the letter and the service just keeps having issues with crashing repeatedly and draining my phone battery real fast.
