### ISSUE TITLE
dynamic change of ports in the UI fails

### ISSUE THREAD

**Issue by brothercorvo** [FreeTAKTeam/FreeTakServer#236]
how to reproduce it:
- in the web UI go to configure
- deactivate the TCP COT service
- click apply
- service is correctly deactivated
- set the port to 8089
- click apply
- port is set back to 8087

**Comment by brothercorvo** [comment]
also an error
```
12:12 | ERROR | FTS.py:118
```
is fired

**Comment by naman108** [comment]
requires associated test to confirm fix

**Comment by brothercorvo** [comment]
successfully Tested it with Pub. Closing issue
