### ISSUE TITLE
sipAddress missing in model

### ISSUE THREAD

**Issue by naman108** [FreeTAKTeam/FreeTakServer#263]
INFO : 2021-12-18 01:09:24,622 : xml_serializer.py:48 : the following property is missing from the FTS model missing cot: ```b'<contact endpoint="*:-1:stcp" phone="phone number" callsign="ex callsign" sipAddress="ip" />'``` attr: sipAddress please open an issue on the FTS github page with this message so that we can address it in future releases

**Comment by brothercorvo** [comment]
fixed in 1.9.8
