### ISSUE TITLE
FTS is re-sending disconnected users

### ISSUE THREAD

**Issue by naman108** [FreeTAKTeam/FreeTakServer#264]
Users who have disconnected are being resent to newly connected users. This could be due to two things.
a) clients disconnects are failing at some stage in the removal process
b) clients are being recreated by another service after disconnection
no errors appear in the logs

**Comment by carlsteyn73** [comment]
Hi, firstly thank you for all the efforts!

I want to report that the fix listed above have not solved the issue for me.
I'm confirming it's only the single change in FTS.py service?

Strange thing, on my one server it fixes it for one device only, but not the rest.

**Comment by carlsteyn73** [comment]
Also, what services are being referred to in: "connected to more than one service" ?

**Comment by naman108** [comment]
> Also, what services are being referred to in: "connected to more than one service" ?

for example, if you had a single device connected over both TCP and SSL these represent two different services

> Hi, firstly thank you for all the efforts!
> 
> I want to report that the fix listed above have not solved the issue for me. I'm confirming it's only the single change in FTS.py service?
> 
> Strange thing, on my one server it fixes it for one device only, but not the rest.

we should be putting out another git commit today with further stability fixes as well as fixes for Federation, this commit will reference this issue and it would be appreciated if you could try again with the new commit.

**Comment by carlsteyn73** [comment]
Excellent. I will keep an eye out and test as soon as it drops

**Comment by naman108** [comment]
this should be addressed in 1.9.8 with improved user management

**Comment by brothercorvo** [comment]
tested and it's OK
