### ISSUE TITLE
Federation Service on FTS 1.9.7 is not working

### ISSUE THREAD

**Issue by carlsteyn73** [FreeTAKTeam/FreeTakServer#266]
When setting up federation between two FTS instances, there is no COT data received by users on either end.

**Comment by naman108** [comment]
yes, we've identified some issues with federation in 1.9.7 and are currently working on it. all commits towards addressing this will reference this issue.

**Comment by brothercorvo** [comment]
THE ISSUE IS FIXED WITH candidate release 1.9.8, we are working now to fix resources side effect of the fix

**Comment by brothercorvo** [comment]
solved in 1.9.8
