### ISSUE TITLE
Privately sent shapes and points don't work with FTS1.9.7 & ATAK4.5

### ISSUE THREAD

**Issue by carlsteyn73** [FreeTAKTeam/FreeTakServer#267]
When sending shapes and points to an individual, it does not work. Except for the mil-standard markers, which do work.
(Broadcasting works for all shapes & markers)

**Comment by naman108** [comment]
when you say don't work, do you mean it's being shared with all clients or not at all?

**Comment by carlsteyn73** [comment]
Yes, as discribed in you question. My timezone's at 4am now. Will share the logs sometime today

**Comment by carlsteyn73** [comment]
Agreed that this bug is minor at this stage. Please excuse my incompetence, but would you be able to explain to me wait logs you'd like me to share?

**Comment by brothercorvo** [comment]
confirmed bug. private send of a shape fails, broadcast of the same works

**Comment by brothercorvo** [comment]
solved in FTS 1.9.8
