### ISSUE TITLE
SSL Cert 

### ISSUE THREAD

**Issue by airjer18** [FreeTAKTeam/FreeTakServer#269]
When trying to connect to a 2nd server after already having a SSL connection to another server, Client fails to autodownload SSL CERT from server even tho I turned off TCP connection in client, made sure user in FTSUI and callsign in ATAK are the same, made sure the DP is not private.   even upon manually downloading SSL cert it will not connect.   via SSL

**Comment by naman108** [comment]
what's your ATAK version, FTS version, logs found in /var/log, and any other configuration changes which may have been made?

**Comment by brothercorvo** [comment]
fixed in FreeTAKServer-1.9.9.0.0.4
