### ISSUE TITLE
Issues with CoT sent by TAK Tracker 4.4

### ISSUE THREAD

**Issue by naman108** [FreeTAKTeam/FreeTakServer#281]
```INFO : 2022-01-09 16:18:01,946 : xml_serializer.py:45 : the following property is missing from the FTS model missing cot: b'<detail>      <takv platform="TakTracker" version="4.4 (1ddd5757)" />      <contact endpoint="*:-1:stcp" callsign="corvo beacon" />      <uid Droid="corvo beacon" />      <__group name="Yellow" role="Team Member" />      <track course="0.0" speed="0.0" />      <precisionlocation altsrc="DTED2" />    </detail>' attr: INTAG please open an issue on the FTS github page with this message so that we can address it in future releases```

**Comment by brothercorvo** [comment]
@naman108 please fix this one
