### ISSUE TITLE
Issue with ATAK XML Format?

### ISSUE THREAD

**Issue by logikal** [FreeTAKTeam/FreeTakServer#284]
I brought this up[ in Discord](https://discord.com/channels/698067185515495436/699262529767211108/935573646976614520) yesterday, and wanted to put it an in issue here after talking with @brothercorvo.

I've got a brand new Ubuntu 20.04 VM, FTS installed via the automated installer. 
Clients are lan-local. ATAK on EUD running `v4.5.1.3 (c99dc7a8) [playstore]`. WinTAK `v4.1.0.231 (CIV)`

WinTAK is a solid connection, no issues. 
EUD is able to connect, but disconnects quickly, and displays `"IO Error, reconnecting"`

FTS logs
```
==> FTS_info.log.1 <==
WARNING : 2022-01-25 16:32:59,524 : ReceiveConnections.py:75 : error in Receive connections listen function timed out

==> FTS_ClientReceptionHandler_debug.log <==
ERROR : 2022-01-25 16:32:59,897 : ClientReceptionHandler.py:109 : there has been an exception in client reception handler timed out
```

After having me connect to the public FTS server, @brothercorvo thinks this might be that the ATAK xml has changed again.

I've attached a tcpdump in case it helps reverse engineer the format. 

[tcpdump.txt](https://github.com/FreeTAKTeam/FreeTakServer/files/7946010/tcpdump.txt)

**Comment by brothercorvo** [comment]
Probably they have changed the XML fields they send in  v4.5.1.3.

**Comment by logikal** [comment]
I did a complete reset of my atak data on my phone, and this wasn't an issue. Not sure what was the cause, but it works as intended now.
