### ISSUE TITLE
RestAPI /ManageGeoObject/getGeoObject broken

### ISSUE THREAD

**Issue by JZNT** [FreeTAKTeam/FreeTakServer#286]
**OS**: Ubuntu 20.04.3
**Installation method**: [FreeTAKHub/Ansible ](https://freetakteam.github.io/FreeTAKServer-User-Docs/Installation/Ansible/Ansible/)(easy_install.sh)

**Issue**: API endpoint /ManageGeoObject/getGeoObject seems broken on 1.9. It is returning "expected string or bytes-like object". Might be related to SQLAlchemy, as the code throws an exception at:
https://github.com/FreeTAKTeam/FreeTakServer/blob/d8cb7996c2ac716349d5836b96b0bb18900d0722/FreeTAKServer/controllers/services/RestAPI.py#L622

**Comment by kfir12345** [comment]
any updates?

**Comment by naman108** [comment]
A test for the fix needs to be written then the fix and test will be pushed together.

**Comment by brothercorvo** [comment]
@naman108 can you fix this one?
