### ISSUE TITLE
AnsibleUndefinedVariable: 'videoserver_ipv4' is undefined from One Touch install

### ISSUE THREAD

**Issue by FelixKitty** [FreeTAKTeam/FreeTakServer#288]
` install the FTS stack from the anisible one touch install onto a clean updated install of Ubuntu 20.04.3 LTS (Focal Fossa) onto a Raspberry Pi 3B.

Ive googled and googled and cant find even a snippet of what went on here.

When we got to the node red install the following occurred 

`Install Node-RED Server (y/n)? (default: y): y

PLAY [Install Node-RED Server] *************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [cleanup /tmp/*] **********************************************************
changed: [localhost]

TASK [common : Include Ubuntu-specific variables] ******************************
ok: [localhost]

TASK [common : Setup] **********************************************************
included: /home/ubuntu/FreeTAKHub-Installation/roles/common/tasks/setup-Ubuntu.yml for localhost

TASK [common : Update apt] *****************************************************
ok: [localhost]

TASK [common : Detect systemctl file] ******************************************
ok: [localhost]

TASK [common : Create systemctl backup] ****************************************
ok: [localhost]

TASK [common : Use systemctl workaround] ***************************************
ok: [localhost]

TASK [nodered : Include Ubuntu-specific variables] *****************************
ok: [localhost]

TASK [nodered : Install] *******************************************************
included: /home/ubuntu/FreeTAKHub-Installation/roles/nodered/tasks/setup-Ubuntu.yml for localhost

TASK [nodered : wait for lock-frontend release] ********************************
ok: [localhost]

TASK [nodered : Install apt dependencies] **************************************
ok: [localhost] => (item=npm)
ok: [localhost] => (item=nodejs)

TASK [nodered : Install packages with npm] *************************************
ok: [localhost] => (item=node-red)
ok: [localhost] => (item=node-red-admin)

TASK [nodered : Install Node-RED nodes with npm] *******************************
ok: [localhost] => (item=node-red-contrib-config)
ok: [localhost] => (item=node-red-dashboard)
ok: [localhost] => (item=node-red-contrib-credentials)

TASK [nodered : Create flows directory] ****************************************
ok: [localhost]

TASK [nodered : Template backup Node-RED flows] ********************************
ok: [localhost] => (item=salute.json)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'videoserver_ipv4' is undefined
failed: [localhost] (item=videochecker.json) => {"ansible_loop_var": "item", "changed": false, "item": "videochecker.json", "msg": "AnsibleUndefinedVariable: 'videoserver_ipv4' is undefined"}

PLAY RECAP *********************************************************************
localhost                  : ok=15   changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 `

**Comment by brothercorvo** [comment]
Raspberry Pi 3 is not supported for Zerotouch installation because it lacks of the resources to run everything , you should install FTS components separately

**Comment by brothercorvo** [comment]
close beacause PI3 is not supported
