### ISSUE TITLE
Unauthenticated Public RestAPI Endpoint

### ISSUE THREAD

**Issue by Securitybits-io** [FreeTAKTeam/FreeTakServer#291]
In the RestAPI there is also the Endpoint _/ManageRoute/postRoute_ which is unauthenticated. While this might not seem interesting at first, it is possible to broadcast new routes (suggested tracks to take) to every End User Device (EUD) connected to the server. This can create two issues, either create a Denial of Service situation where a malicious user can fill the entire map with routes, making it impossible to use the map in the EUD. The second scenario might be to create a route on which possible users might take and therefor control some of the paths and direct users into bad situations.

![Unauthenticated-Endpoint](https://user-images.githubusercontent.com/14073684/154237142-9d5c1649-15fa-49d5-9f4f-68bbd64dae3e.jpg)

**Comment by brothercorvo** [comment]
fixed in 1.9.8.5
