### ISSUE TITLE
Hardcoded Flask Secrets Key - "Privilege Escalation"

### ISSUE THREAD

**Issue by Securitybits-io** [FreeTAKTeam/FreeTakServer#292]
In the sourcecode there are 3 relevant places that the Flask Secrets Key are hardcoded. Flask signs all their client sessions with this secret key, usually defined in an _Environment Variable_. In this case though there's these three places that these are hardcoded into. 

![Github_Flask_Secret-key](https://user-images.githubusercontent.com/14073684/154238555-6f4fdf89-126b-487b-bde4-10dac1370a41.jpg)

This gives a malicious user the ability to sign their own cookies (using for example: [Flask-Unsign](https://github.com/Paradoxis/Flask-Unsign)), and internally change the UID of the current user and assume any other user, for example UID 1 which is the Admin. (Privilege Escalation)

Another interessting issue that you run into aswell is that having two Flask servers with the same _secret key_ makes it possible for a user to reuse a UID 1 cookie from Server A, and apply that cookie to Server B logging in to the same UID 1. (Lateral movement/Authentication bypass).

**Comment by brothercorvo** [comment]
fixed in 1.9.8.5
