### ISSUE TITLE
CoT are not refreshed in the database and look stationary through the API

### ISSUE THREAD

**Issue by clemosm** [FreeTAKTeam/FreeTakServer#297]
I wanted to use the API to track clients connected to the server. Using the API, or directly looking into the database, I can see all clients and CoTs. However, their coordinates (and orientation) only update when they join the server, and stay the same after that, although they appear to move on the map for all ATAK clients.

I don't know if it is a bug or if I'm doing something wrong here.
I'm currently testing this on a local Windows server, but plan on hosting my FTS on an Ubuntu server in the future, if that matters.

**Comment by brothercorvo** [comment]
please try to replicate this using:
1. Ubuntu
2. a real moving target (e.g. a car)

**Comment by brothercorvo** [comment]
@clemosm we tried to replicate the issue but the function seems to be working

**Comment by brothercorvo** [comment]
fixed in FreeTAKServer-1.9.9.0.0.4
