### ISSUE TITLE
Wont run first time install wizard. 

### ISSUE THREAD

**Issue by Jamie-Morgon** [FreeTAKTeam/FreeTakServer#306]
followed instructions in user guide - https://freetakteam.github.io/FreeTAKServer-User-Docs/Installation/Linux/Install/y

no issues when running "pip check FreeTakServer "
when i run "sudo python3 -m FreeTAKServer.controllers.services.FTS"

output from sudo python3 -m pip install FreeTAKServer[ui] in attached .txt file

[output from sudo python3 -m pip install FreeTAKServer[ui].txt](https://github.com/FreeTAKTeam/FreeTakServer/files/8248243/output.from.sudo.python3.-m.pip.install.FreeTAKServer.ui.txt)

pip check FreeTakServer = **No broken requirements found.**

sudo python3 -m FreeTAKServer.controllers.services.FTS  = 
**Cannot find CA locally so generating one
Generating Key...
Generating Key...
start 213
starting now
running api
0.0.0.0
8080
(1248) wsgi starting up on http://0.0.0.0:8080
start 213
starting SSL now
0.0.0.0
8443
(1249) wsgi starting up on https://0.0.0.0:8443
event event about to be created
CoTService started
SSL CoTService started
ssl cot service starting
started federation federate service
server started
server started

 running ssl**

just hangs, any help / direction would be appreciated

cheers.

**Comment by brothercorvo** [comment]
this is the same as #301 , that has fixed with https://github.com/FreeTAKTeam/FreeTakServer/pull/305 . We are testing the fix. However the server should be available, even if the console indicates otherwise

**Comment by brothercorvo** [comment]
solved in 1.9.8.8

**Comment by widom8ker** [comment]
This has not been solved because Ive been having the sane issues on 1.9.9.2
