### ISSUE TITLE
update serialization so that empty marti tag isnt added

### ISSUE THREAD

**Issue by naman108** [FreeTAKTeam/FreeTakServer#318]

**Comment by brothercorvo** [comment]
@naman108 its fixed in FreeTAKServer-1.9.9.0.0.4?

**Comment by brothercorvo** [comment]
@naman108 can we close this?

**Comment by naman108** [comment]
I need to validate this is still the case but AFAIK this has not been fixed

**Comment by brothercorvo** [comment]
@naman108 I think I tested that and we can close it....

**Comment by naman108** [comment]
closing on the assumption you've tested
