### ISSUE TITLE
FTS v1.9.8.8 public produces connection error upon connecting to server

### ISSUE THREAD

**Issue by b1uebu11** [FreeTAKTeam/FreeTakServer#322]
When connecting to FTS v1.9.8.8 public via android ATAK (CIV) v4.6.0.4, a system UI notification appears indicating a connection error, however, connection remains successful.

Hosting FTSv1.9.8.8 on Xubuntu 20.04

System UI notification
![connection error FTS 1 9 8 8 public](https://user-images.githubusercontent.com/86221991/164432271-ad64fc64-bbee-4353-8d18-c33bbe8b0bdb.PNG)

SSL error on FTS server
![ssl cert error](https://user-images.githubusercontent.com/86221991/164432280-9af08cad-a657-46c0-ad2d-dabab9fb1d30.PNG)

**Comment by b1uebu11** [comment]
Just to note, this was identified via an existing installation that was previously operating without errors, then a day later upon connecting, this connection error appeared. I then installed on a fresh instance on Xubuntu and the connection error appears.

**Comment by brothercorvo** [comment]
Try to restart FTS.  SSL conn3ction has some issues we are currently fixing

**Comment by brothercorvo** [comment]
SSL is now fixed in FreeTAKServer-1.9.9.0.0.4

**Comment by b1uebu11** [comment]
@brothercorvo, awesome mate, thank you
