### ISSUE TITLE
Add repeater service

### ISSUE THREAD

**Issue by brothercorvo** [FreeTAKTeam/FreeTakServer#323]
chech also #194 
This service acts as a repeater for certain messages. Any messages added to this service
 * will be repeated out to all interested parties at regular intervals. This service will
 * adapt itself to the configuration specified in the config file. Those parameters are:
 * 
 * KEY					| TYPE		| DEFAULT	| DESCRIPTION
 * --------------------------------------------------------------------------------------------------------------------
 * enable					| Boolean | false		| determines if this service will be started or not
 * maxAllowedRepeatables	| Integer 	| int max	| the maximum number of messages that this service will manage
 * periodMillis				| Integer	| 10000		| the period in milliseconds in which this service will initiate dissemination

**Comment by naman108** [comment]
<h4>COT Repeater requirements:</h4>

 - Must be exposed via the API
 - Must send all messages to every new client upon connection.
 - Must support persistency of messages through restarts
 - Must complete execution in under 0.01 seconds

---

<h4>COT Repeater risks:<h4>

 - Interference with existing systems by adding a new call.
 - Increases the load on the system with every new connection
---
<h4>COT Repeater milestones:</h4>
 
 - [ ] Complete core functionality
	 - [ ] Define and document actions.
		 - [ ] Create
		 - [ ] Read
		 - [ ] Delete
	- [ ] Implement component outline.
	- [ ] Implement Persistency strategy.
	- [ ] Create tests for each action
- [ ] Add API support
	- [ ] Define endpoints in swagger definition.
	- [ ] serialization support for json -> node
	- [ ] add action call to cot_repeater
	- [ ] write tests for endpoints in postman
- [ ] Integrate with existing system
	- [ ] Add action call on client connection from tcp_cot_service to cot_repeater
	- [ ] Add action call on client connection from ssl_cot_service to cot_repeater

**Comment by brothercorvo** [comment]
@naman108  the requirements are correct.
you should add the following:

- the function is part of the FTS COT Manager component
- the function extends [postgeoobject](https://freetakteam.github.io/FreeTAKServer-User-Docs/API/REST_APIDoc/#postgeoobject) by adding a single optional Boolean parameter repeater=true 
- Postman is a proprietary software and we do not have licenses, instead we should use OpenAPI swagger for tests. I created some  in [TAKtest](https://github.com/FreeTAKTeam/FreeTAKTest/tree/main/TestData/OpenAPISwagger)

**Comment by naman108** [comment]
> @naman108 the requirements are correct. you should add the following:
> 
> * the function is part of the FTS COT Manager component
> * the function extends [postgeoobject](https://freetakteam.github.io/FreeTAKServer-User-Docs/API/REST_APIDoc/#postgeoobject) by adding a single optional Boolean parameter repeater=true
> * Postman is a proprietary software and we do not have licenses, instead we should use OpenAPI swagger for tests. I created some  in [TAKtest](https://github.com/FreeTAKTeam/FreeTAKTest/tree/main/TestData/OpenAPISwagger)

updated
