### ISSUE TITLE
Issues within the UI after install

### ISSUE THREAD

**Issue by mrburch** [FreeTAKTeam/FreeTakServer#325]
I have completed an installed of FTS 1.9.8.8 Public on Ubuntu 20.04 in Azure. When I log into the UI for the first time I get an connection error and several of the graphs will not load. On the users page the users list will not load and I am unable to change the default user.

During install of the current version there was no YAML setup so all IP configurations to mainconfig and config were made manually.

What am I missing here?
![ftshomescreen](https://user-images.githubusercontent.com/104367374/165097790-f24e2b26-fa5d-4338-b12b-25ca302b554d.png)
![ftsuserscreen](https://user-images.githubusercontent.com/104367374/165097804-885ddb0d-9649-4955-a8a6-8aacee86813d.png)

**Comment by brothercorvo** [comment]
this is the same issue as #330

**Comment by brothercorvo** [comment]
solved
