### ISSUE TITLE
Question about SSL connection to server

### ISSUE THREAD

**Issue by MartinStokelj** [FreeTAKTeam/FreeTakServer#339]
Hi, I have a question about SSL connection with the server. 
I am trying to connect my application with the TakServer.
Why there are two certificates and how do I need to handle them during the connection. 
I need to make pull or get requests, to which link address? 
All I know for now is that I have 2 certificates and domain name of the custom server like ssl://XXX:8089
So how can I establish connection from my application? WinTAK is able to connect to this server nicely, but I want to integrate this in to my application.

**Comment by brothercorvo** [comment]
without details on the application you want to build it's difficult to help. In general FTS uses the OpenSSL library. The certs are coming in a zipped file that you may need to unzip. Refer to your language libraries on how to handle OpenSSL

**Comment by MartinStokelj** [comment]
@brothercorvo I have C# application for flying drones and I want to connect to TAK server to be able to send placemarks/markers to others on that server. And also share a video with metadata.
So I will check OpenSSL library, thanks for the info.

**Comment by brothercorvo** [comment]
The FreeTAK UAS is doing the exact same but uses the API instead of XML, it's Java but close enough to C3 you can check that repository. Embedding metadata into the video is something we have not solved, so if you find a solution and you share it would be great!

**Comment by MartinStokelj** [comment]
I am already getting video with metadata from the camera, I just forward the video to TAK with ffmpeg.
