### ISSUE TITLE
Initial setup doesn't ask to create a YAML file, how to make one manually?

### ISSUE THREAD

**Issue by mindracer13** [FreeTAKTeam/FreeTakServer#340]
I followed the installation procedures to the tee for Ubuntu 20.04, and every single time I try, when I get to the Configure/Run part of the instructions and execute "sudo python3 -m FreeTAKServer.controllers.services.FTS", I should be asked If i want to create a yaml file and ask me my ip address, but it doesnt.  It runs the server straight away and I can only find a DB file on /opt but no yaml file.

root@sparta:/opt# sudo python3 -m FreeTAKServer.controllers.services.FTS
CA found locally, not generating a new one
Certificate file exists, aborting.
Certificate file exists, aborting.
something
start 213
starting now
running api
0.0.0.0
8080
(30070) wsgi starting up on http://0.0.0.0:8080
start 213
starting SSL now
0.0.0.0
8443
(30073) wsgi starting up on https://0.0.0.0:8443

I've tried re-installing a new VM 3 times and the same thing happens.  Is there a command i can run to get that wizard to create a yaml file and ask me my IP?

**Comment by brothercorvo** [comment]
@HeroesLament please add the instructions how to setup the flag in the docs

**Comment by 0ddBall** [comment]
I also have this issue. While I think it would be great to update the documentation for creating the file manually, can we fix that setup command? I am happy to help with any log files that can help you troubleshoot the issue. Running Ubuntu 22.04 on clean install using Hyper-V with a Windows 10 2104 host. What else can I do to help?

**Comment by gbradg** [comment]
Having this same issue on Ubuntu 20.04. I manually created the YAML file according to the screenshot in the docs (https://user-images.githubusercontent.com/60719165/142766660-daac490a-3c0c-4089-b3b8-40c5e520c1ff.png) but things are still not good. Interested in updated documentation or setup command as well.

**Comment by Shot-Iron-6728** [comment]
I am also running into this same issue. Any updates on a fix for this?

**Comment by Shot-Iron-6728** [comment]
@HeroesLament , @brothercorvo Just wanted to check in on this. We are hoping to get a TAK server up and running soon. I am happy to provide screenshots or help however I can.

**Comment by tsvtx** [comment]
Go into the config file located in /usr/local/lib/python3.8/dist-packages/FreeTAKServer/controllers/configuration and modify MainConfig.py. You'll want to change the value for first_start from False to True and restart per the instructions. You should then get the prompt to create the yml file.

**Comment by Shot-Iron-6728** [comment]
@tsvtx This worked. Thank you for the info!

**Comment by brothercorvo** [comment]
the @tsvtx solution has been added here:
https://github.com/FreeTAKTeam/FreeTAKServer-User-Docs/blob/main/docs/docs/Installation/Troubleshooting/troubleshooting.md

case closed

**Comment by brothercorvo** [comment]
fixed in 1.9.9.6
