### ISSUE TITLE
Drop point component

### ISSUE THREAD

**Issue by brothercorvo** [FreeTAKTeam/FreeTakServer#359]
a COT need to be drop of a map. this function need to be isolated an d accessible trough the Facade

**Comment by brothercorvo** [comment]
add a example Bus. rule to the drop point

**Comment by brothercorvo** [comment]
Basic test is done and it works
@dlc-ariel do you have the business rule added that I can test?

**Comment by dlc-ariel** [comment]
@brothercorvo Can you clarify what you mean by business rule?

**Comment by brothercorvo** [comment]
e.g if a Marker is of type hostile, add a text "Hostile!" to the remark field
check out the emergency component for an example
