### ISSUE TITLE
SSL Connection breaking after multiple disconnects

### ISSUE THREAD

**Issue by brothercorvo** [FreeTAKTeam/FreeTakServer#368]
The SSL CoT Service is not running after a period of time.
![image](https://user-images.githubusercontent.com/60719165/187905383-98392730-3da5-4a4a-938a-6c0dde49c4f4.png)

**target system installed with PIP**

FTS-SSL_CoT_Service_error.log

Is showing this error.
![image](https://user-images.githubusercontent.com/60719165/187905710-dcc34b3f-2076-4296-94cc-0cc1f1c76d40.png)

Port 8089 is not used by any other service.
If i kill the process , fts is starting it again but SSL is showing its down in the web ui

can normally be addressed by this workaround:
https://github.com/FreeTAKTeam/FreeTAKServer-User-Docs/blob/main/docs/docs/Installation/Linux/SOcketIssue.md

also being discussed here:
https://discord.com/channels/1001155141329748049/1003723063927505058/1014606204577792030

reported here:
https://freetakteam.discourse.group/t/fts-ssl-cot-breaks-after-time/13

**Comment by brothercorvo** [comment]
this may be relevant to understand the issue:
https://stackoverflow.com/questions/72319941/what-do-socket-sol-socket-and-socket-so-reuseaddr-in-python
and also this:
"_Most of the time, a socket file is removed automatically when the process that created it terminates. However, sometimes a socket file may be left behind, and this can cause problems if a new process tries to create a socket with the same name. In this case, you can remove the socket file manually_."

**Comment by brothercorvo** [comment]
Services listening to several ports on the target machine
![image](https://user-images.githubusercontent.com/60719165/187906666-d9ce0f43-bbe4-4461-a65e-8a6d8937ee16.png)

**Comment by brothercorvo** [comment]
![image](https://user-images.githubusercontent.com/60719165/187907122-f0d9365e-2ce2-493f-b931-92bc727262e6.png)

**Comment by DanielHeinze** [comment]
[FTS-Log.zip](https://github.com/FreeTAKTeam/FreeTakServer/files/9510692/FTS-Log.zip)

**Comment by brothercorvo** [comment]
it appears that this message
```
DEBUG : 2022-08-17 05:39:54,433 : ClientReceptionHandler.py:107 : data received b'<event version="2.0" uid="3fa80587-e554-4821-bad4-4bdb62ff9ba1" type="a-n-G" time="2022-08-17T05:39:53.631Z" start="2022-08-17T05:39:53.631Z" stale="2023-08-17T05:39:53.631Z" how="h-g-i-g-o"><point lat="52.3828223" lon="11.8199915" hae="88.91" ce="9999999.0" le="9999999.0" /><detail><status readiness="true" /><archive /><archive /><remarks /><contact callsign="Mine 4 dummy" /><precisionlocation altsrc="DTED2" /><usericon iconsetpath="f8f7f666-8b28-4b57-9fbb-e48e61d33b79/Iron Sites/Structure Destroyed.png" /><color argb="-1" /><link uid="ANDROID-cc97c3ea-dc9b-468f-b01c-ea323e8b61e9" production_time="2022-08-17T04:31:36.273Z" type="a-f-G-U-C" parent_callsign="SR18 N9" relation="p-p" /></detail></event>'
```
is provoking an error in the parser
```
ERROR : 2022-08-17 05:39:54,460 : ClientReceptionHandler.py:86 : Exception other than broken pipe in monitor for data function not well-formed (invalid token): line 2, column 636

Traceback (most recent call last):
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1693, in feed
```

but line 636 seems to be OK....

**Comment by brothercorvo** [comment]
duplicates of #447 
this is depending on the CRL as documented [here](https://freetakteam.github.io/FreeTAKServer-User-Docs/Installation/Troubleshooting/SocketIssue/). We have now created a script to fix it
