### ISSUE TITLE
Sever crash 2022 14/11

### ISSUE THREAD

**Issue by sa2kaa** [FreeTAKTeam/FreeTakServer#399]
I can see in syslog that the server crashed. Is there any interest in logs from the event?

**Comment by hickey** [comment]
It may be useful to see the logs to try to diagnose what might have happened. At the very least it will give an indication if there is a hidden issue somewhere in the code or if it is something that we can anticipate and handle better. 

So yes if you still have the syslog output around post it here so we can take a look. Also it would be useful to know what version you have installed or what commit you installed from. 

Thanks.

**Comment by sa2kaa** [comment]
According to the welcome message it is version 1.9.9.6 Public. I followed the install instruction from the Wiki and did not install directly from GitHub, that is pip3 was mostly used. The server crashes repeatedly to it seems easy to reproduce the problem if some narrowed down root cause tests needs to be done. I suspect a memory leek somewhere but don't have any logging for that. Apart from the FreeTakServer no other software apart from Fail2Ban has been installed in the Ubuntu 20 Desktop  version I use.

Appended excerpt from syslog
[221144.syslog.4.excerpt.txt](https://github.com/FreeTAKTeam/FreeTakServer/files/10088753/221144.syslog.4.excerpt.txt)
