### ISSUE TITLE
Relocation of server runtime files

### ISSUE THREAD

**Issue by hickey** [FreeTAKTeam/FreeTakServer#408]
With the work that @dlc-ariel is doing on cleaning up some of linting errors in #400, I was prompted by the latest errors being produced to investigate further. 

The latest error was attempting to make a directory in the FTS package install directory in preparation for placing data package files within the directory. This is a bad practice and opens the FTS installation to the possiblity of being compromised. The FTS installation directory should be treated as an immutable location and no additional files should be placed there. 

Work involved:

- [x] Update `MainConfig` defaults with paths that are outside of where FTS gets installed (there may be a path or two that reference files distributed with the package--`ExCheckFilePath`?--that would not need to be changed)
- [ ] Add a note to the 2.0 release notes of this breaking change
- [ ] Add documentation to user docs to assist users on migrating their data to new locations (this doc should also be referenced in release notes)

**Comment by hickey** [comment]
@brothercorvo I just realized that this was occurring and think that it needs to be addressed for the `2.0` release.

**Comment by naman108** [comment]
I'm going to begin working on this today so that we can have functional CI system before pulling my or @dlc-ariel pulls.

**Comment by naman108** [comment]
this commit has changed the default path for persistent data to the /home/[user]/.fts directory. This seems like a sane configuration for the following reasons.
1. we can be certain that the user calling FTS can access this path
2. the data is almost certainly persisted unless deleted intentionally or the user is deleted

**Comment by brothercorvo** [comment]
> this commit has changed the default path for persistent data to the /home/[user]/.fts directory. This seems like a sane configuration for the following reasons.
> 
> 1. we can be certain that the user calling FTS can access this path.
> 2. the data is almost certainly persisted unless deleted intentionally or the user is deleted.
> 3. the directory is secure (other standard users can't modify it) by default and can have it's access permissions changed by the calling user.
> 4. we can be certain it exists on any given linux distribution
 Possible downside is that we don't know a fix name for the user, so users with less proficiency will be lost looking for configuration files.
 
OPT seems to be a reasonable place

> If we don’t package it using standard tools, such as [dpkg](https://man7.org/linux/man-pages/man1/dpkg.1.html) or [rpm](https://man7.org/linux/man-pages/man8/rpm.8.html), we’ll most likely put all of the files related to CompanyApplication in a single directory. So we’ll have the binaries, libraries, and configuration together. They won’t be separated into different locations as a traditional UNIX system would have them.


>

**Comment by naman108** [comment]
@brothercorvo while opt addresses 2 and 4, 1 and 3 may or may not be true. I was under the impression there were several users who wanted to be able to run as a non-root user so this would eliminate that option by default furthermore, a given user may or may not be able to modify access to the /opt directory rendering it less secure in some situations. The main pro I see is that it is common across users making it usefull if two users want to be able to start the same FTS instance. Am I missing anything in this evaluation?

**Comment by hickey** [comment]
Given that a lot of the time FTS is installed as a Python package, it might be necessary to add a bit of code to `MainConfig` that checks for the existence of `/home/fts/.fts` and attempts to create it if it does not exists. If there is a failure to create the directory, then we should probably throw an exception to prevent the startup of FTS and warn the user to correct the situation.

**Comment by naman108** [comment]
so it seems the evaluation is to use the `/opt/fts/` directory for all persistent data as the convention is that correct @hickey, @HeroesLament, @brothercorvo?

**Comment by hickey** [comment]
Since some of the conversation was over in the Signal, here is some of the conversation for prosperity and where it can be referenced in the future. 

> @naman108 
> in response to issue #408 what do people think of using the /home/[user]/.fts directory for persistent FTS data

> I recommend it because it does not require root, works by default with every user and is almost guaranteed to be persistent

> I will write up a more formal explanation of the rational but I just wanted to notify people that if anyone has a better default persistency location please bring it up here https://github.com/FreeTAKTeam/FreeTakServer/issues/408

> @hickey
> While I like putting it in the user's home directory and makes it a fairly standard place to go for a lot of installations, I am not sure we need to put it in `.fts`. I really tend to dislike putting files in hidden directories unless people should not be mucking with said files without good reason or good knowledge of what they are doing.
I would opt for something like `fts` or `fts_data` or something like that.

> I would also say that we follow the normal convention of using the env var of FTS_HOME to locate the root of the persistance files.

> @HeroesLament 
> And seeing as the FTS process itself does not really exist as a user tool, /opt/fts_core and /opt/fts_ui would be how I would do them

> @hickey 
> Yes, and I think we need to put that in the docs that there is the "default" location for personal / small installs, but for production level installs the recommendation might be something like /opt/fts or /usr/local/fts....

>Quite possible. I had not put much thought into the UI stuff yet.

> Or what if FTS_HOME was /opt/fts and FTS core expects to have a sub directory there for its files and UI is expecting a sub directory there for its files. So /opt/fts/core and /opt/fts/ui. This allows for further expansion if something like hub or a future component needs to store files/config there.

> Take note of the above comment. The more I think about it, it is probably the best solution going forward.

> @brothercorvo 
> Opt\FTS is good. If we can bend pypy to use it

> @hickey 
> Pypy will not be a problem. The FTS package is not going there. It will still be installed where all the python packages get installed. The /opt/fts structure is only for the data files that FTS uses. Database, config, certs, data packages, etc.

> It just occurred to me with the last comment that the YAML configuration should probably reside in /opt/fts (/opt/fts/config.yaml or /opt/fts/fts_config.yaml or whatever) and then both core and UI can point to the same file rather than duplicate the config and have mismatched settings.

**Comment by hickey** [comment]
Alright, back to your original question: Yes, `/opt/fts` is a good option. `~USER/fts` is not a bad one either and the good news is that the home directory model will generally have less issues with permissions. But it does tend to "hide" data a bit more. But the end user would be able to control this location by setting `$FTS_HOME`, but for a default I think either of these two would be good options. 

Also take note that I would prefer to have a subdirectory for FTS core and another subdirectory for UI. If they are on the same machine, then both would be populated and if they are on separate machines then on directory would be populated and the other empty or non-existent. Of course UI may not really have any files that it needs to store locally--I have not really been looking at that code base.
