### ISSUE TITLE
separate ExCheck code from Datapackage controller

### ISSUE THREAD

**Issue by brothercorvo** [FreeTAKTeam/FreeTakServer#411]
Currently the code for the ExCheck Function is part of: 
services/DataPackageServer.py

it's necessary to:

- separate excheck functions from the main 
e.g.
```
@app.route("/hello")
def hello():
    return componentName.Hello()
```

**Comment by brothercorvo** [comment]
I think this is in progress @dlc-ariel ?

**Comment by dlc-ariel** [comment]
@brothercorvo This is technically complete since it has been extracted to the excheck controller under the excheck component. The excheck component is being reworked but it unrelated to this issue so I believe this can be closed.
