### ISSUE TITLE
The TAK server's identity could not be verified

### ISSUE THREAD

**Issue by Josh-SMU** [FreeTAKTeam/FreeTakServer#415]
Set up on Debian 11 using the One Touch setup method. When I try to connect to the server with ATAK using credentials and SSL on 8089 it returns this error. SSL is up per the dashboard and the user list.

**Comment by Josh-SMU** [comment]
Also as a separate note, there was no documentation on which ports needed to be opened in the firewall, nor on default admin credentials. I opened 1880, 8080, 8087, 8089, 8443, 9000, and 19023

**Comment by Josh-SMU** [comment]
From FTS_ReceiveConnections_info.log:

<code>
INFO : 2022-11-22 11:24:24,875 : ReceiveConnections.py:100 : client connected
WARNING : 2022-11-22 11:24:24,875 : ReceiveConnections.py:114 : error in Receive connections listen function list index out of range
INFO : 2022-11-22 11:24:29,110 : ReceiveConnections.py:100 : client connected
WARNING : 2022-11-22 11:24:29,110 : ReceiveConnections.py:114 : error in Receive connections listen function list index out of range
INFO : 2022-11-22 11:24:29,767 : ReceiveConnections.py:100 : client connected
WARNING : 2022-11-22 11:24:29,767 : ReceiveConnections.py:114 : error in Receive connections listen function list index out of range
WARNING : 2022-11-22 11:24:29,977 : ReceiveConnections.py:85 : ssl error thrown in connection attempt [SSL: HTTP_REQUEST] http request (_ssl.c:1123)
WARNING : 2022-11-22 11:24:30,047 : ReceiveConnections.py:85 : ssl error thrown in connection attempt [SSL: HTTP_REQUEST] http request (_ssl.c:1123)
WARNING : 2022-11-22 11:24:30,115 : ReceiveConnections.py:85 : ssl error thrown in connection attempt [SSL: HTTP_REQUEST] http request (_ssl.c:1123)
WARNING : 2022-11-22 11:24:30,182 : ReceiveConnections.py:85 : ssl error thrown in connection attempt [SSL: HTTP_REQUEST] http request (_ssl.c:1123)
WARNING : 2022-11-22 11:24:30,251 : ReceiveConnections.py:85 : ssl error thrown in connection attempt [SSL: HTTP_REQUEST] http request (_ssl.c:1123)
WARNING : 2022-11-22 11:24:30,319 : ReceiveConnections.py:85 : ssl error thrown in connection attempt [SSL: HTTP_REQUEST] http request (_ssl.c:1123)
WARNING : 2022-11-22 11:24:30,397 : ReceiveConnections.py:85 : ssl error thrown in connection attempt [SSL: HTTP_REQUEST] http request (_ssl.c:1123)
WARNING : 2022-11-22 11:24:30,465 : ReceiveConnections.py:85 : ssl error thrown in connection attempt [SSL: HTTP_REQUEST] http request (_ssl.c:1123)
WARNING : 2022-11-22 11:24:30,785 : ReceiveConnections.py:85 : ssl error thrown in connection attempt [SSL: HTTP_REQUEST] http request (_ssl.c:1123)
WARNING : 2022-11-22 11:24:36,562 : ReceiveConnections.py:85 : ssl error thrown in connection attempt EOF occurred in violation of protocol (_ssl.c:1123)
WARNING : 2022-11-22 11:25:36,564 : ReceiveConnections.py:114 : error in Receive connections listen function timed out
WARNING : 2022-11-22 11:26:36,602 : ReceiveConnections.py:114 : error in Receive connections listen function timed out
WARNING : 2022-11-22 11:27:36,653 : ReceiveConnections.py:114 : error in Receive connections listen function timed out
WARNING : 2022-11-22 11:28:36,686 : ReceiveConnections.py:114 : error in Receive connections listen function timed out
WARNING : 2022-11-22 11:29:36,717 : ReceiveConnections.py:114 : error in Receive connections listen function timed out
WARNING : 2022-11-22 11:30:36,767 : ReceiveConnections.py:114 : error in Receive connections listen function timed out
WARNING : 2022-11-22 11:31:36,785 : ReceiveConnections.py:114 : error in Receive connections listen function timed out
WARNING : 2022-11-22 11:32:36,842 : ReceiveConnections.py:114 : error in Receive connections listen function timed out
WARNING : 2022-11-22 11:32:50,714 : ReceiveConnections.py:85 : ssl error thrown in connection attempt [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1123)
WARNING : 2022-11-22 11:33:01,287 : ReceiveConnections.py:85 : ssl error thrown in connection attempt [SSL: PEER_DID_NOT_RETURN_A_CERTIFICATE] peer did not return a certificate (_ssl.c:1123)
WARNING : 2022-11-22 11:33:02,032 : ReceiveConnections.py:85 : ssl error thrown in connection attempt [SSL: PEER_DID_NOT_RETURN_A_CERTIFICATE] peer did not return a certificate (_ssl.c:1123)
WARNING : 2022-11-22 11:34:02,086 : ReceiveConnections.py:114 : error in Receive connections listen function timed out
WARNING : 2022-11-22 11:35:02,144 : ReceiveConnections.py:114 : error in Receive connections listen function timed out
WARNING : 2022-11-22 11:36:02,182 : ReceiveConnections.py:114 : error in Receive connections listen function timed out
WARNING : 2022-11-22 11:37:02,226 : ReceiveConnections.py:114 : error in Receive connections listen function timed out
WARNING : 2022-11-22 11:38:02,266 : ReceiveConnections.py:114 : error in Receive connections listen function timed out
WARNING : 2022-11-22 11:39:02,303 : ReceiveConnections.py:114 : error in Receive connections listen function timed out
WARNING : 2022-11-22 11:40:02,360 : ReceiveConnections.py:114 : error in Receive connections listen function timed out
WARNING : 2022-11-22 11:41:02,412 : ReceiveConnections.py:114 : error in Receive connections listen function timed out
WARNING : 2022-11-22 11:42:02,472 : ReceiveConnections.py:114 : error in Receive connections listen function timed out
WARNING : 2022-11-22 11:43:02,473 : ReceiveConnections.py:114 : error in Receive connections listen function timed out
WARNING : 2022-11-22 11:44:02,481 : ReceiveConnections.py:114 : error in Receive connections listen function timed out
INFO : 2022-11-22 11:46:57,698 : ReceiveConnections.py:100 : client connected
WARNING : 2022-11-22 11:46:57,698 : ReceiveConnections.py:114 : error in Receive connections listen function 'str' object has no attribute 'findall'
WARNING : 2022-11-22 11:48:05,720 : ReceiveConnections.py:114 : error in Receive connections listen function timed out
</code>

**Comment by brothercorvo** [comment]
Can you tell the exact ATAK version  you are using?

**Comment by brothercorvo** [comment]
@naman108  there nothing in 4.7 indicating a change in SSL, however I found in 4.6.1.0
**Security: Update openssl usages by commo and video libraries to 1.1.1n**

**Comment by Josh-SMU** [comment]
Is that something I can/must update on the FreeTAK server or would it need updates to the code?

**Comment by Josh-SMU** [comment]
Or will this need to be added for a milestone?

**Comment by Josh-SMU** [comment]
How should I go about testing that? My setup is ATAK 4.7 and the latest FreeTAK server on Debian Bookworm

**Comment by bmkrol823** [comment]
@Josh-SMU We have tested against our ZeroTouch install of FreeTAKServer 1.9.9.6 which is hosted on Ubuntu 20.04 and have not been able to replicate the issue. Can you inform us of the version of FreeTAKServer you have installed? Also, can you confirm that you generated the certificates from the FreeTAKServer UI?

**Comment by Josh-SMU** [comment]
I did generate the user certs in the UI and the radial gauge on the dashboard is good for SSL. One thing to note is that I had to run the ZeroTouch installer twice as the first time it skipped a couple components, not sure why. Is there a simple way to see which components are installed or skipped, and also install logs?

**Comment by Josh-SMU** [comment]
My version of FTS is 1.9.9.2

**Comment by Josh-SMU** [comment]
Ok I have figured out the issue. It was operator error with importing SSL certs. 

To change the password from the default is it sufficient to simply change the string in the yaml file under /opt?
