### ISSUE TITLE
meeting notes service architecture sync natha and giu Dec 8

### ISSUE THREAD

**Issue by naman108** [FreeTAKTeam/FreeTakServer#436]
*  - [ ] implement SUB methods based on proposed libraries
*  - [ ] implement PUSH methods based on proposed libraries
*  - [ ] refactor domain into core component
*  - [ ] create parsing architecture
* *  - [ ] refactor parsing into core component
*  - [ ] implement database type mapping
*  - [ ] encapsulate fts tcpcot service into digitalpy tcp service
*  - [ ] define SUB methods
*  - [ ] define service startup sequence
*  - [ ] define service manager @brothercorvo 
*  - [ ] implement dynamic object instantiation during parsing
*  - [ ] implement domain extension support per component

**Comment by brothercorvo** [comment]
architect component persistency strategy @brothercorvo
