### ISSUE TITLE
Webmap not showing clients

### ISSUE THREAD

**Issue by Josh-SMU** [FreeTAKTeam/FreeTakServer#453]
All ports per the Pi install instructions are open in the firewall (this should be documented in the main wiki?) but when I connect a client via ATAK they do not appear on the webmap. The home page of the UI shows they are connected.

**Comment by Josh-SMU** [comment]
In NodeRed I see that something has an error, could this be related?

![Screenshot](https://user-images.githubusercontent.com/111187832/207956776-9ce64add-9615-4f05-a186-900954b04850.png)

**Comment by Josh-SMU** [comment]
I deleted and re-imported the .json and configured the items per the white balloon markers. However, the webmap still shows nothing. From the webmap log, I see the following:

<code>
15 Dec 13:45:38 - [info] Starting flows
15 Dec 13:45:38 - [info] [worldmap:TAK Map] started at /tak-map
15 Dec 13:45:38 - [info] Started flows
15 Dec 13:45:38 - [info] [debug:909491c9.80e7c]
{ payload: '/opt/webMAP_config.json', _msgid: 'a76a6a0.1709c98' }
15 Dec 13:45:38 - [error] [DataIn:deb4de55.05379] TypeError: Cannot read property 'length' of undefined
15 Dec 13:45:38 - [info] [debug:storing]
{ payload: '/opt/webMAP_config.json', _msgid: 'a76a6a0.1709c98' }
15 Dec 13:45:38 - [error] [tcp request:FTS Server] connect failed IPADDRESS:8087
15 Dec 13:45:38 - [info] Node-RED Dashboard not found - ui_worldmap not installed.
</code>

**Comment by brothercorvo** [comment]
You need to install the worldmap node

**Comment by Josh-SMU** [comment]
How can I do that?

**Comment by Josh-SMU** [comment]
I looked through the code in the Hub installation repo and figured out how to install the node via npm install. However, not sure exactly how to import so I did so as per below (how should this be done, and do I have to hit Deploy at the top right once the flow is configured correctly?):

![Screenshot](https://user-images.githubusercontent.com/111187832/208745305-a100af6c-2aff-41f2-9e4c-901c7426efe8.png)

Also, the flows seem to lose connection after some time as you can see from the error under FTS Server. Not sure why this is happening.

**Comment by Crankinator** [comment]
Josh,

Double click the "FTS Server" bubble, and for the address, use 127.0.0.1, and the port as 8087. You should see it connect, and then you should be able to reconnect a client. You should start seeing things propagate.

Let me know if that works for you.

**Comment by Josh-SMU** [comment]
This worked, thank you!

And thank you for your patience.

**Comment by PA8E** [comment]
Finally, got it working with the last tip! Thanks!
