### ISSUE TITLE
Revoked SSL Certificate for just created user

### ISSUE THREAD

**Issue by greenygh0st** [FreeTAKTeam/FreeTakServer#455]
When I try to connect with an SSL user in my FreeTAKServer instance I am observing the following error in the log:

```
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate revoked (_ssl.c:1131)
ssl error thrown in connection attempt [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate revoked (_ssl.c:1131)
```

TCP connections work fine. This is a 99% vanilla setup from the ZeroTouch/Ansible script, the only change was adding the user.

Thanks!

**Comment by brothercorvo** [comment]
FTS has a function to revoke a SSL cert when the corresponding user is deleted. If your certification has been created by another server or instance of FTS you would get this error

**Comment by brothercorvo** [comment]
check also this https://freetakteam.github.io/FreeTAKServer-User-Docs/Troubleshooting/SocketIssue/
