### ISSUE TITLE
First start fails to change

### ISSUE THREAD

**Issue by naman108** [FreeTAKTeam/FreeTakServer#551]
in FTS 2.0 Beta (and possibly earlier versions) the first start variable is not being set resulting in the config wizard being triggered on every start.

**Comment by mikevb3** [comment]
I had this error too trying to make a small dockerized version, the wizard starts anyway even when the yaml is on the opt directory.

Is there any way I can help @naman108 ?

**Comment by brothercorvo** [comment]
currently the flag is in the memory of the OS, we are moving it to a persistent place @mikevb3.
If you have experience with the docker, you can help us creating a 2.0 docker release

**Comment by naman108** [comment]
> I had this error too trying to make a small dockerized version, the wizard starts anyway even when the yaml is on the opt directory.
> 
> Is there any way I can help @naman108 ?

If you had any ideas as to how we could set and persist the first start variable as false after the config wizard finished running feel free to make a pull. Right now we're just not sure of the best approach because there are so many options.

**Comment by RadioAndrea** [comment]
Merged and fixed in #577
