### ISSUE TITLE
It can be seen from the server log that itak has been linked to the server, but the coordinates and message cannot be displayed on itak

### ISSUE THREAD

**Issue by caesarsywu** [FreeTAKTeam/FreeTakServer#592]
![WX20230521-230232@2x](https://github.com/FreeTAKTeam/FreeTakServer/assets/134217479/ee2d024d-a0f7-4fc9-aefa-cd9da08d11ea)

**Comment by deltatango2** [comment]
I had similar issues, also found that when tcp payloads were sent I received a response form the server but nothing added to the map.  I shutdown FTS and ran taky to test, and the same payload that didn't work with FTS worked with taky.  At least for TCP non SSL, I can confirm a vanilla install ubuntu 20 all defaults on python 3.8 is yielding odd results.

**Comment by brothercorvo** [comment]
please retest with 2.1

**Comment by brothercorvo** [comment]
tested with iTAK and 2.1 and could not replicate, closing for now
