### ISSUE TITLE
Config File Not Being Read

### ISSUE THREAD

**Issue by HeroesLament** [FreeTAKTeam/FreeTakServer#625]
It doesn't read the FTSconfig.yaml file at all located at the persistency path.

**Comment by HeroesLament** [comment]
In MainConfig.py, this evaluates as false:

```if os.path.exists(config_file):```

Causing this to not be ran:

```cls._instance.read_yaml_config(config_file)```

Meaning we never actually apply settings in FTSconfig.yaml. This is due to:

```# if config_file not specified, check env or use default location
if config_file == None:
    config_file = str(os.environ.get('FTS_CONFIG_PATH', MainConfig._defaults["yaml_path"]))```
 
Setting the config_file to:

```{'default': '/opt/fts/FTSConfig.yaml', 'type': <class 'str'>}```

Instead of:

```'/opt/fts/FTSConfig.yaml'```

Which we want.

**Comment by naman108** [comment]
The pull request associated with this issue has been merged, can it be closed?
