### ISSUE TITLE
Unknown COT attribute

### ISSUE THREAD

**Issue by dustinmcintire** [FreeTAKTeam/FreeTakServer#631]
I'm reviewing the COT data in the FTS_XmlSerializer_info.log file and find a bunch of messages from the XML parser that it doesn't know what to do with the messages coming from the latest ATAK on the play store.  The ATAK version is 4.10.0.14.  I'm not sure if this is an ATAK config issue or a FTS issue.  I'm posting in case there is something valuable in seeing the log output.

`INFO : 2023-09-26 16:30:30,918 : xml_serializer.py:49 : the following property is missing from the FTS model missing cot: b'<event version="2.0" uid="ANDROID-2fe3f21ba66d8140" type="a-f-G-U-C" time="2023-09-26T16:30:31.652Z" start="2023-09-26T16:30:31.652Z" stale="2023-09-26T16:36:46.652Z" how="h-g-i-g-o" access="Undefined"><point lat="0.0" lon="0.0" hae="9999999.0" ce="9999999.0" le="9999999.0" /><detail><takv os="33" version="4.10.0.14 (3e3ea750)[playstore].1695219266-CIV" device="ONEPLUS LE2115" platform="ATAK-CIV" /><contact xmppUsername="maniac@openfire.5gflyer.internal" endpoint="*:-1:stcp" phone="+860002" callsign="MANIAC" /><uid Droid="MANIAC" /><__group role="Team Member" name="Cyan" /><status battery="100" /><track course="289.62090156834336" speed="0.0" /></detail></event>' attr: access please open an issue on the FTS github page with this message so that we can address it in future releases`

**Comment by HeeebsInc** [comment]
@dustinmcintire we are having the same issue.  Have you found a solution/cause for this?  Im thinking it could be ATAK version 4.0API but im not entirely sure

**Comment by brothercorvo** [comment]
fixed in 2.1
