### ISSUE TITLE
User data package does not import in ATAK 4.10

### ISSUE THREAD

**Issue by themanbornwithin** [FreeTAKTeam/FreeTakServer#651]
FTS 2.1 RC1, UI 2.1

I tried importing a user data package into ATAK 4.10. It appears to import and no errors are given, but the server does not appear in the connection list.

I downgraded to 4.8, and was able to successfully import the data package and connect to the server. I then upgraded to 4.10, the server was still present and I was able to successfully connect to the server.

**Comment by brothercorvo** [comment]
it seems that they have changed the way it works. I will try to replicate that.

**Comment by brothercorvo** [comment]
testing

**Comment by brothercorvo** [comment]
![Image](https://github.com/FreeTAKTeam/FreeTakServer/assets/60719165/e1837bda-9824-46bf-b928-25f0e01bac8e)

I could successfully import certs into ATAK 5.10. so closing for now
