### ISSUE TITLE
pip install failure

### ISSUE THREAD

**Issue by erentar** [FreeTAKTeam/FreeTakServer#669]
I followed the instructions on https://freetakteam.github.io/FreeTAKServer-User-Docs/Installation/Linux/Installation/

PyYAML 6.0 fails to install, while PyYAML 6.0.1 succeeds. The python package should install 6.0.1 instead.

Further information about the problem is available at https://github.com/yaml/pyyaml/issues/736

following dockerfile will reproduce the error
```
from fedora
run sudo dnf update -b -y
run dnf group install "Development Tools" "C Development Tools and Libraries" -y
run sudo dnf install python3 python3-pip cairo cairo-devel python3-cairo python3-cairo-devel python3-gevent python3-lxml python3-virtualenv -y
run virtualenv venv
run source venv/bin/activate
run pip install wheel pycairo
run pip install FreeTAKServer[ui]
```

**Comment by nir2602** [comment]
PYYAML is now version 6.0.1.
