### ISSUE TITLE
DataPackageServer.py

### ISSUE THREAD

**Issue by jwmcdowell278** [FreeTAKTeam/FreeTakServer#71]
line 197 and line 146 should look like:

return IP+':'+str(HTTPPORT)+"/Marti/api/sync/metadata/"+hash+"/tool"

to avoid getting an error (TypeError: can only concatenate str (not "int") to str) when uploading packages to the server.

**Comment by naman108** [comment]
how are you setting IP?

**Comment by naman108** [comment]
also what branch is this in?

**Comment by jwmcdowell278** [comment]
I am using:  sudo python -m FreeTAKServer.controllers.Orchestrator -CoTPort 8099 -IP (your IP) -APIPort 9999
It is the master branch.

**Comment by naman108** [comment]
Ok you should install with pip as master needs to be updated

**Comment by brothercorvo** [comment]
solved in 1.0
