### ISSUE TITLE
Permission Denied on config.py

### ISSUE THREAD

**Issue by akecj7** [FreeTAKTeam/FreeTakServer#712]
I have searched and came up empty handed, and after many, many, tries of trying getting TAKServer to install properly on a Pi4 and following the instructions [here](https://freetakteam.github.io/FreeTAKServer-User-Docs/Installation/RaspberryPi/Installation/).  I am finally at the point trying to edit the config.py file.  When doing so with the following the steps in the configuration portion of the process using the line input of /usr/local/lib/python3.10/dist-packages/FreeTAKServer-UI/config.py (I know the walk thru is using python 3.11, but this is what was installed with the TAK server and I did run, python3 --version to confirm) and it spits out a Persmision denied error.  Any thoughts on a fix?  Thank you in advance,

**Comment by ki6uve** [comment]
We are working on the underlying issue, but the work around is to change your user status by running this command from the CLI: sudo su -

After that you should be able to edit the file.

**Comment by akecj7** [comment]
No change.

<img width="591" alt="image" src="https://github.com/FreeTAKTeam/FreeTakServer/assets/17371244/895377e0-7cdd-4191-9f99-3eb8205977b5">

**Comment by phreed** [comment]
If you want to edit the config.py file you will need an editor. 
(You are trying to run a python script with bash, that will not work.)
If you have `vi` installed, you can try: 
`vi /usr/local/lib/python3.10/dist-packages/FreeTAKServer-UI/config.py`

**Comment by phreed** [comment]
Did you install with ZT installer?

**Comment by ki6uve** [comment]
or nano: sudo nano /usr/local/lib/python3.10/dist-packages/FreeTAKServer-UI/config.py

**Comment by akecj7** [comment]
> Did you install with ZT installer?

I did

Using the sudo nano worked to get me into the ability to check the configuration.  Thanks for the help on this.  now how do I know if I need to update any of the settings?

**Comment by phreed** [comment]
I believe this is a documentation issue.
The pages where reconfiguration is described are:
* https://freetakteam.github.io/FreeTAKServer-User-Docs/Installation/mechanism/Ansible/ZeroTouchInstall/#reconfiguration
* https://freetakteam.github.io/FreeTAKServer-User-Docs/administration/Operation/fts-config/
* https://freetakteam.github.io/FreeTAKServer-User-Docs/Troubleshooting/fts-server/
* https://freetakteam.github.io/FreeTAKServer-User-Docs/Troubleshooting/fts-ui-server/

These pages have been recently updated (2024 May 9).
Can we pick up this discussion about the documentation on the [Discord channel](https://discord.gg/m8cBzQM2te) #doc-dev

**Comment by akecj7** [comment]
> I believe this is a documentation issue. The pages where reconfiguration is described are:
> 
> * https://freetakteam.github.io/FreeTAKServer-User-Docs/Installation/mechanism/Ansible/ZeroTouchInstall/#reconfiguration
> * https://freetakteam.github.io/FreeTAKServer-User-Docs/administration/Operation/fts-config/
> * https://freetakteam.github.io/FreeTAKServer-User-Docs/Troubleshooting/fts-server/
> * https://freetakteam.github.io/FreeTAKServer-User-Docs/Troubleshooting/fts-ui-server/
> 
> These pages have been recently updated (2024 May 9). Can we pick up this discussion about the documentation on the [Discord channel](https://discord.gg/m8cBzQM2te) #doc-dev

Thanks, we can probably close this at this point and pickup on Discord.
