### ISSUE TITLE
Can't renew SSL certs

### ISSUE THREAD

**Issue by Josh-SMU** [FreeTAKTeam/FreeTakServer#714]
The SSL certs were created upon install and valid for one year. They have since expired but there is no script or function to renew them. This should be broken out as a separate script for ease of maintenance. After pouring through the scripts it seems the only way to renew or recreate them is through a python support script which is called by ansible on install.

**Comment by Josh-SMU** [comment]
Broke my install trying to figure it out so installed newest version.

**Comment by naman108** [comment]
for future reference, details here on regenerating the `ca` and `crl` is here https://freetakteam.github.io/FreeTAKServer-User-Docs/Troubleshooting/SocketIssue/
