### ISSUE TITLE
Documentation site is broken

### ISSUE THREAD

**Issue by metasim** [FreeTAKTeam/FreeTakServer#724]
Going here:

https://freetakteam.github.io/FreeTAKServer-User-Docs/Usage/API/REST_APIDoc/

results in a page that looks like this:

<img width="576" alt="image" src="https://github.com/user-attachments/assets/dc2f8b08-f5d9-4810-9cfc-e2f968f80c6d">

Browser console shows this:
 
<img width="572" alt="image" src="https://github.com/user-attachments/assets/332de253-6657-4bd2-8621-aba759b1e85c">

**Comment by omon316** [comment]
https://freetakteam.github.io/FreeTAKServer-User-Docs/

**Comment by phreed** [comment]
Things have been reorganized so any bookmarked links may fail. 
The current link is https://freetakteam.github.io/FreeTAKServer-User-Docs/API/REST_API_Doc/
