### ISSUE TITLE
I made a container for this project

### ISSUE THREAD

**Issue by integrii** [FreeTAKTeam/FreeTakServer#74]
https://github.com/integrii/FreeTakServerContainer

Feel free to integrate/steal this into the main project.  If you are receptive, I can make a PR to add it to your README.md.

**Comment by brothercorvo** [comment]
thank you for your contribution. Can the container be updated using PIP

**Comment by integrii** [comment]
You just rebuild the container each time you want a new one and push a new tag.

For example, the container is at `integrii/atak:latest` right now, but if we want to update it, we would rebuild it with a new tag, such as `integrii/atak:v1.2.3`.

Then later if you have a future version, you can easily roll back to `v1.2.3` by just switching back to the tag.  

If you are at the root of my repository, you can build the container into any tag you like with the following:

`docker build -t <docker hub user>/atak:<some tag> .`

The built container will download whatever version of `atak` was on `pip` at the time you ran the build.

Then, to make this container available to the world, you would run a push:

`docker push <docker hub user>/atak:<some tag>`

**Comment by brothercorvo** [comment]
> https://github.com/integrii/FreeTakServerContainer

I have added the reference to the readme file
