### ISSUE TITLE
Inquiry: Official API Specification for FreeTAKServer

### ISSUE THREAD

**Issue by nicopace** [FreeTAKTeam/FreeTakServer#744]
Hello FreeTAKServer maintainers and community,

I've been working with the FreeTAKServer project and noticed that there have been recent pull requests (#646, #611, #619) implementing and modifying mission-related functionality and ExCheck integration.

I'm wondering if there is an official API specification (such as OpenAPI/Swagger) available for the FreeTAKServer, particularly for the mission and ExCheck-related endpoints. If so, could you please point me to where I can find it?

If there isn't an official API spec yet, would it be helpful for the project if the community worked on creating one? This could potentially:

1. Improve developer onboarding and understanding of the API
2. Facilitate easier integration for users of the FreeTAKServer
3. Serve as living documentation that evolves with the project

Thank you for your time and for maintaining this valuable project!

Best regards,
Nico Pace

**Comment by brothercorvo** [comment]
hello Niko,
FTS official API specification is documented here :
https://freetakteam.github.io/FreeTAKServer-User-Docs/API/REST_API_Doc/
we have an OperAPi version of the specification that is located in our test repository:
https://github.com/FreeTAKTeam/FreeTAKTest/blob/main/TestData/OpenAPISwagger/FullFTSAPI.yaml 
this is considered to be work in progress, so you can help develop that .
In FTS release 3.0 we plan to migrate all payload to proper JSON schemas
