### ISSUE TITLE
Bad exception when client closes

### ISSUE THREAD

**Issue by bcgordon3** [FreeTAKTeam/FreeTakServer#77]
If I close ATAK on a client after it has attached to FTS, I will get the following exception:
`Orchestrator.py:286 : exception in client data, data processing within main run function error in general data processing data is -1`

When that client reconnects (say reopens ATAK), they will get some information, like PLI, but not others, like marker drops.

Full disconnect message sequence is this:
```
INFO : 2020-07-24 15:59:20,053 : Orchestrator.py:286 : exception in client data, data processing within main run function error in general data processing data is -1
INFO : 2020-07-24 15:59:20,064 : Orchestrator.py:182 : initiating client disconnection
ERROR : 2020-07-24 15:59:20,065 : Orchestrator.py:213 : there has been an error in a clients disconnection while adding information to the database no such table: Users
INFO : 2020-07-24 15:59:20,065 : Orchestrator.py:286 : exception in client data, data processing within main run function error in general data processing data is -1
```

**Comment by brothercorvo** [comment]
solved in 1.0
