### ISSUE TITLE
Cannot get the server to start.

### ISSUE THREAD

**Issue by greenwich90** [FreeTAKTeam/FreeTakServer#87]
I am running Ubuntu 18 LTS on an AWS EC2 instance.

`sudo  python3 -m FreeTAKServer.controllers.FTS -DataPackageIP [YourIP]` - returns _no such module FreeTAKServer.controllers.FTS_

I have tried running the command within the application directory folder and I get the same result.

Within the FTS CLI all commands return with _error in processing your request function returned bad data_.

Any ideas what could be causing this/what I am doing wrong?

Cheers

**Comment by naman108** [comment]
Sorry about that main README.md has to be fixed however if you downloaded with pip check out the pypi branch README.md
