### ISSUE TITLE
Server Fails to start in CLI

### ISSUE THREAD

**Issue by netgeak** [FreeTAKTeam/FreeTakServer#88]
I am installing on Ubuntu 18 and when I run sudo python3 -m FreeTAKServer.controllers.services.FTS -DataPackageIP 192.168.1.2
it starts up. But if I use the CLI is get error in processing your request function returned bad data.
I used install instructions from Pypi readme. is there something I am missing with the setup?
Thanks.

**Comment by naman108** [comment]
is the cli being run on the same machine?

**Comment by netgeak** [comment]
Yes, same machine.  I run sudo python3 -m FreeTAKServer.views.CLI, issue command start_all and enter the required info.
at the end it gives the error.

**Comment by greenwich90** [comment]
I also get this error.

I have not been able to get the server to start whatsoever though unfortunately.

**Comment by netgeak** [comment]
Issue the following commands and you should be able to start the server using "sudo python3 -m FreeTAKServer.controllers.services.FTS -DataPackageIP "myIP" command.
sudo -H python3 -m pip install flask_socketio 
sudo -H python3 -m pip install flask_cors
Since version 1.1 those modules dont seam to get installed.
Hope that helps.

**Comment by greenwich90** [comment]
@netgeak That work, 

Thank you.

**Comment by netgeak** [comment]
Just a side note. When I run the server I get constant reconnects with the atak client.

**Comment by greenwich90** [comment]
@netgeak does the client actually drop connection? (TAK server turns red) How often does this happen?

I have not experienced this but have only done limited testing. Last night I had a stable connection with 4 clients, but I was only testing for around an hour.

**Comment by naman108** [comment]
> Just a side note. When I run the server I get constant reconnects with the atak client.

have you changed any user configurations like adding email or xmpp address?

**Comment by netgeak** [comment]
I am seeing this with WinTak, I added xmpp but it was doing the same thing prior.  All I see in the server console is multiple "Handling conn data" statements. Client disconnect happens every 30 seconds roughly.

**Comment by naman108** [comment]
could you send the FTS error log please?

**Comment by netgeak** [comment]
[FTS_warning.log](https://github.com/FreeTAKTeam/FreeTakServer/files/5375069/FTS_warning.log)

**Comment by naman108** [comment]
It seems that you haven't disabled xmpp properly as it's still being sent on connection.

**Comment by netgeak** [comment]
I've disabled it in WinTak, still see the constant disconnects.

**Comment by naman108** [comment]
try removing the logs restart FTS restart wintak and reconnect if the error persists send the error log.

**Comment by netgeak** [comment]
Will do. Thanks

**Comment by netgeak** [comment]
We can close this issue. I had to unload the Tak Chat plugin in WinTAK then the disconnects quit.
Thanks for all your help.
