### ISSUE TITLE
Enabling email address or VoIP contact info causes Data Reception Timeout when connecting

### ISSUE THREAD

**Issue by sniporbob** [FreeTAKTeam/FreeTakServer#92]
### Symptom:
Connecting to FTS is not possible with certain contact preferences configured. ATAK appears to connect for approx 30 seconds (green dot) but then a Data Reception Timeout error occurs and the indicator goes red. A short time later the indicator turns green and the process repeats.

### Cause:
From the device preferences menu, if either/both of the following is true it no longer becomes possible to start a connection to FTS:

1) Publish Preferred Email: enter any email address
and/or
2) Publish VoIP Number: Use IP Address

This only causes a problem when connecting to FTS. If _already connected_ to FTS, then the settings above can be changed and the connection to the server will continue unaffected.

If at any point the email address field is cleared and the VoIP setting is changed to No VoIP, connectivity will be restored. It may take one connect/disconnect cycle to fully clear whatever issue is going on.

### Replication:
Screenshot attached of the location where the settings can be changed. Also attached are two preference files, should you find them useful. Loading "ATAK-pref-cause-disconnect.pref" will set both of these settings to a state where it is not possible to connect to FTS. Loading "ATAK-pref-no-disconnect.pref" will set both settings to a state where connectivity is restored. You can unzip and place the files in /atak/config/prefs/ then load them using Load Preferences under the Device Preferences category of settings.

Pre) Disconnect from any currently connected FTS

1a) Go to the Publish Preferred Email setting and type in an email address
and//or
1b) Go to the Publish VoIP Number setting and change it to Use IP Address
2) Enable a connection to FTS
3) Wait ~30 seconds for disconnect to occur

![Screenshot_20201011-124802](https://user-images.githubusercontent.com/8404483/95688788-9026fd00-0bc1-11eb-9f1f-d4124b986e5a.png)
[ATAK-prefs.zip](https://github.com/FreeTAKTeam/FreeTakServer/files/5361883/ATAK-prefs.zip)

**Comment by naman108** [comment]
thank you very much this has been reprodused and will be addressed in the next sub version release at which point this issue will be closed, however if you happen upon any other connection breaking configuration please continue in the thread thank you.
