### ISSUE TITLE
WinTAK-CIV FreeTakServer connection issues

### ISSUE THREAD

**Issue by xsystemgr** [FreeTAKTeam/FreeTakServer#94]
I try to connect WinTAK but without success but ATAK connected without any issues. Have any CoT issue compatibility with WinTAK?

**Comment by naman108** [comment]
what version of FTS are you using, do you have an email or xmpp address set?

**Comment by xsystemgr** [comment]
I have installed it the pip install way and not ask me , there is a configuration file?, I have not seen it . The version is 1.1
